FROM node:10

ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME

COPY . .

# If you are building your code for production
# RUN npm install --only=production
RUN npm install

# run the database migrations and seeding
CMD ["npm", "run", "setup"]
