{{- if .Values.pgBackRest.s3.createS3Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgBackRest.s3.s3Secret }}
type: Opaque
data:
  s3.conf: {{ include "postgres.s3.full" . | b64enc }}
{{- end }}