 drop trigger if exists audit_activity on biohub.activity;
 drop trigger if exists audit_administrative_activity_type on biohub.administrative_activity_type;
 drop trigger if exists audit_administrative_activity_status_type on biohub.administrative_activity_status_type;
 drop trigger if exists audit_ancillary_species on biohub.ancillary_species;
 drop trigger if exists audit_funding_source on biohub.funding_source;
 drop trigger if exists audit_climate_change_initiative on biohub.climate_change_initiative;
 drop trigger if exists audit_first_nations on biohub.first_nations;
 drop trigger if exists audit_iucn_conservation_action_level_1_classification on biohub.iucn_conservation_action_level_1_classification;
 drop trigger if exists audit_iucn_conservation_action_level_3_subclassification on biohub.iucn_conservation_action_level_3_subclassification;
 drop trigger if exists audit_project_activity on biohub.project_activity;
 drop trigger if exists audit_management_action_type on biohub.management_action_type;
 drop trigger if exists audit_no_sample_permit on biohub.no_sample_permit;
 drop trigger if exists audit_investment_action_category on biohub.investment_action_category;
 drop trigger if exists audit_project_climate_initiative on biohub.project_climate_initiative;
 drop trigger if exists audit_project_first_nation on biohub.project_first_nation;
 drop trigger if exists audit_project_funding_source on biohub.project_funding_source;
 drop trigger if exists audit_project_iucn_action_classification on biohub.project_iucn_action_classification;
 drop trigger if exists audit_project_management_actions on biohub.project_management_actions;
 drop trigger if exists audit_project_participation on biohub.project_participation;
 drop trigger if exists audit_project_permit on biohub.project_permit;
 drop trigger if exists audit_project_region on biohub.project_region;
 drop trigger if exists audit_system_constant on biohub.system_constant;
 drop trigger if exists audit_webform_draft on biohub.webform_draft;
 drop trigger if exists audit_system_user_role on biohub.system_user_role;
 drop trigger if exists audit_project_type on biohub.project_type;
 drop trigger if exists audit_project_role on biohub.project_role;
 drop trigger if exists audit_stakeholder_partnership on biohub.stakeholder_partnership;
 drop trigger if exists audit_user_identity_source on biohub.user_identity_source;
 drop trigger if exists audit_system_role on biohub.system_role;
 drop trigger if exists audit_administrative_activity on biohub.administrative_activity;
 drop trigger if exists audit_system_user on biohub.system_user;
 drop trigger if exists audit_project on biohub.project;
 drop trigger if exists audit_focal_species on biohub.focal_species;
 drop trigger if exists audit_iucn_conservation_action_level_2_subclassification on biohub.iucn_conservation_action_level_2_subclassification;
 drop trigger if exists audit_project_attachment on biohub.project_attachment;

 create trigger audit_activity before insert or update or delete on biohub.activity for each row execute procedure tr_audit_trigger();
 create trigger audit_administrative_activity_type before insert or update or delete on biohub.administrative_activity_type for each row execute procedure tr_audit_trigger();
 create trigger audit_administrative_activity_status_type before insert or update or delete on biohub.administrative_activity_status_type for each row execute procedure tr_audit_trigger();
 create trigger audit_ancillary_species before insert or update or delete on biohub.ancillary_species for each row execute procedure tr_audit_trigger();
 create trigger audit_funding_source before insert or update or delete on biohub.funding_source for each row execute procedure tr_audit_trigger();
 create trigger audit_climate_change_initiative before insert or update or delete on biohub.climate_change_initiative for each row execute procedure tr_audit_trigger();
 create trigger audit_first_nations before insert or update or delete on biohub.first_nations for each row execute procedure tr_audit_trigger();
 create trigger audit_iucn_conservation_action_level_1_classification before insert or update or delete on biohub.iucn_conservation_action_level_1_classification for each row execute procedure tr_audit_trigger();
 create trigger audit_iucn_conservation_action_level_3_subclassification before insert or update or delete on biohub.iucn_conservation_action_level_3_subclassification for each row execute procedure tr_audit_trigger();
 create trigger audit_project_activity before insert or update or delete on biohub.project_activity for each row execute procedure tr_audit_trigger();
 create trigger audit_management_action_type before insert or update or delete on biohub.management_action_type for each row execute procedure tr_audit_trigger();
 create trigger audit_no_sample_permit before insert or update or delete on biohub.no_sample_permit for each row execute procedure tr_audit_trigger();
 create trigger audit_investment_action_category before insert or update or delete on biohub.investment_action_category for each row execute procedure tr_audit_trigger();
 create trigger audit_project_climate_initiative before insert or update or delete on biohub.project_climate_initiative for each row execute procedure tr_audit_trigger();
 create trigger audit_project_first_nation before insert or update or delete on biohub.project_first_nation for each row execute procedure tr_audit_trigger();
 create trigger audit_project_funding_source before insert or update or delete on biohub.project_funding_source for each row execute procedure tr_audit_trigger();
 create trigger audit_project_iucn_action_classification before insert or update or delete on biohub.project_iucn_action_classification for each row execute procedure tr_audit_trigger();
 create trigger audit_project_management_actions before insert or update or delete on biohub.project_management_actions for each row execute procedure tr_audit_trigger();
 create trigger audit_project_participation before insert or update or delete on biohub.project_participation for each row execute procedure tr_audit_trigger();
 create trigger audit_project_permit before insert or update or delete on biohub.project_permit for each row execute procedure tr_audit_trigger();
 create trigger audit_project_region before insert or update or delete on biohub.project_region for each row execute procedure tr_audit_trigger();
 create trigger audit_system_constant before insert or update or delete on biohub.system_constant for each row execute procedure tr_audit_trigger();
 create trigger audit_webform_draft before insert or update or delete on biohub.webform_draft for each row execute procedure tr_audit_trigger();
 create trigger audit_system_user_role before insert or update or delete on biohub.system_user_role for each row execute procedure tr_audit_trigger();
 create trigger audit_project_type before insert or update or delete on biohub.project_type for each row execute procedure tr_audit_trigger();
 create trigger audit_project_role before insert or update or delete on biohub.project_role for each row execute procedure tr_audit_trigger();
 create trigger audit_stakeholder_partnership before insert or update or delete on biohub.stakeholder_partnership for each row execute procedure tr_audit_trigger();
 create trigger audit_user_identity_source before insert or update or delete on biohub.user_identity_source for each row execute procedure tr_audit_trigger();
 create trigger audit_system_role before insert or update or delete on biohub.system_role for each row execute procedure tr_audit_trigger();
 create trigger audit_administrative_activity before insert or update or delete on biohub.administrative_activity for each row execute procedure tr_audit_trigger();
 create trigger audit_system_user before insert or update or delete on biohub.system_user for each row execute procedure tr_audit_trigger();
 create trigger audit_project before insert or update or delete on biohub.project for each row execute procedure tr_audit_trigger();
 create trigger audit_focal_species before insert or update or delete on biohub.focal_species for each row execute procedure tr_audit_trigger();
 create trigger audit_iucn_conservation_action_level_2_subclassification before insert or update or delete on biohub.iucn_conservation_action_level_2_subclassification for each row execute procedure tr_audit_trigger();
 create trigger audit_project_attachment before insert or update or delete on biohub.project_attachment for each row execute procedure tr_audit_trigger();

