kind: ConfigMap
apiVersion: v1
metadata:
  name: sims-pipeline-config
  namespace: af2668-dev
immutable: false
data:
  config: |
    {
      "name": "sims",
      "version": "1.0.0",
      "module": {
        "db": "sims-db",
        "api": "sims-api",
        "app": "sims-app"
      },
      "api": {
        "pr": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "tz": "America/Vancouver",
            "backboneApiHost": "https://api-dev-biohub-platform.apps.silver.devops.gov.bc.ca",
            "backboneIntakePath": "/api/dwc/submission/queue",
            "backboneArtifactIntakePath": "/api/artifact/intake",
            "backboneIntakeEnabled": false,
            "bctwApiHost": "https://moe-bctw-api-dev.apps.silver.devops.gov.bc.ca",
            "critterbaseApiHost": "https://moe-critterbase-api-dev.apps.silver.devops.gov.bc.ca/api",
            "elasticsearchURL": "http://es01.a0ec71-dev:9200",
            "elasticsearchTaxonomyIndex": "taxonomy_3.0.0",
            "s3KeyPrefix": "sims-pr",
            "logLevel": "debug",
            "cpuRequest": "50m",
            "cpuLimit": "400m",
            "memoryRequest": "100Mi",
            "memoryLimit": "2Gi",
            "replicas": "1",
            "replicasMax": "2"
          }
        },
        "dev": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "staticApiUrl": "api-dev-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "dev-sims.apps.silver.devops.gov.bc.ca",
            "tz": "America/Vancouver",
            "backboneApiHost": "https://api-dev-biohub-platform.apps.silver.devops.gov.bc.ca",
            "backboneIntakePath": "/api/dwc/submission/queue",
            "backboneArtifactIntakePath": "/api/artifact/intake",
            "backboneIntakeEnabled": false,
            "bctwApiHost": "https://moe-bctw-api-dev.apps.silver.devops.gov.bc.ca",
            "critterbaseApiHost": "https://moe-critterbase-api-dev.apps.silver.devops.gov.bc.ca/api",
            "elasticsearchURL": "http://es01.a0ec71-dev:9200",
            "elasticsearchTaxonomyIndex": "taxonomy_3.0.0",
            "s3KeyPrefix": "sims",
            "logLevel": "debug",
            "cpuRequest": "50m",
            "cpuLimit": "400m",
            "memoryRequest": "100Mi",
            "memoryLimit": "2Gi",
            "replicas": "1",
            "replicasMax": "2"
          }
        },
        "test": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi"
          },
          "deploy": {
            "namespace": "af2668-test",
            "nodeEnv": "production",
            "staticApiUrl": "api-test-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "test-sims.apps.silver.devops.gov.bc.ca",
            "tz": "America/Vancouver",
            "backboneApiHost": "https://api-test-biohub-platform.apps.silver.devops.gov.bc.ca",
            "backboneIntakePath": "/api/dwc/submission/queue",
            "backboneArtifactIntakePath": "/api/artifact/intake",
            "backboneIntakeEnabled": false,
            "bctwApiHost": "https://moe-bctw-api-test.apps.silver.devops.gov.bc.ca",
            "critterbaseApiHost": "https://moe-critterbase-api-test.apps.silver.devops.gov.bc.ca/api",
            "elasticsearchURL": "http://es01.a0ec71-dev:9200",
            "elasticsearchTaxonomyIndex": "taxonomy_3.0.0",
            "s3KeyPrefix": "sims",
            "logLevel": "info",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi",
            "replicas": "2",
            "replicasMax": "4"
          }
        },
        "prod": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi"
          },
          "deploy": {
            "namespace": "af2668-prod",
            "nodeEnv": "production",
            "staticApiUrl": "api-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "sims.apps.silver.devops.gov.bc.ca",
            "staticAppVanityUrl": "sims.nrs.gov.bc.ca",
            "tz": "America/Vancouver",
            "backboneApiHost": "https://api-biohub-platform.apps.silver.devops.gov.bc.ca",
            "backboneIntakePath": "/api/dwc/submission/queue",
            "backboneArtifactIntakePath": "/api/artifact/intake",
            "backboneIntakeEnabled": false,
            "bctwApiHost": "https://moe-bctw-api-prod.apps.silver.devops.gov.bc.ca",
            "critterbaseApiHost": "https://moe-critterbase-api-prod.apps.silver.devops.gov.bc.ca/api",
            "elasticsearchURL": "http://es01.a0ec71-prod:9200",
            "elasticsearchTaxonomyIndex": "taxonomy_3.0.0",
            "s3KeyPrefix": "sims",
            "logLevel": "warn",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi",
            "replicas": "2",
            "replicasMax": "4"
          }
        }
      },
      "app": {
        "pr": {
          "build": {
            "namespace": "af2668-tools",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "5Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "siteminderLogoutURL": "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi",
            "maxUploadNumFiles": 10,
            "maxUploadFileSize": 52428800,
            "biohubFeatureFlag": "true",
            "cpuRequest": "50m",
            "cpuLimit": "200m",
            "memoryRequest": "100Mi",
            "memoryLimit": "333Mi",
            "replicas": "1",
            "replicasMax": "1"
          }
        },
        "dev": {
          "build": {
            "namespace": "af2668-tools",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "5Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "staticApiUrl": "api-dev-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "dev-sims.apps.silver.devops.gov.bc.ca",
            "siteminderLogoutURL": "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi",
            "maxUploadNumFiles": 10,
            "maxUploadFileSize": 52428800,
            "biohubFeatureFlag": "true",
            "cpuRequest": "50m",
            "cpuLimit": "200m",
            "memoryRequest": "100Mi",
            "memoryLimit": "333Mi",
            "replicas": "1",
            "replicasMax": "1"
          }
        },
        "test": {
          "build": {
            "namespace": "af2668-tools",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "5Gi"
          },
          "deploy": {
            "namespace": "af2668-test",
            "nodeEnv": "production",
            "staticApiUrl": "api-test-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "test-sims.apps.silver.devops.gov.bc.ca",
            "siteminderLogoutURL": "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi",
            "maxUploadNumFiles": 10,
            "maxUploadFileSize": 52428800,
            "biohubFeatureFlag": "false",
            "cpuRequest": "50m",
            "cpuLimit": "500m",
            "memoryRequest": "100Mi",
            "memoryLimit": "500Mi",
            "replicas": "2",
            "replicasMax": "3"
          }
        },
        "prod": {
          "build": {
            "namespace": "af2668-tools",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "5Gi"
          },
          "deploy": {
            "namespace": "af2668-prod",
            "nodeEnv": "production",
            "staticApiUrl": "api-sims.apps.silver.devops.gov.bc.ca",
            "staticAppUrl": "sims.apps.silver.devops.gov.bc.ca",
            "staticAppVanityUrl": "sims.nrs.gov.bc.ca",
            "siteminderLogoutURL": "https://logon7.gov.bc.ca/clp-cgi/logoff.cgi",
            "maxUploadNumFiles": 10,
            "maxUploadFileSize": 52428800,
            "biohubFeatureFlag": "false",
            "cpuRequest": "50m",
            "cpuLimit": "500m",
            "memoryRequest": "100Mi",
            "memoryLimit": "500Mi",
            "replicas": "2",
            "replicasMax": "3"
          }
        }
      },
      "database": {
        "pr": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "sourceContextDir": "database",
            "dbSetupDockerfilePath": "./.docker/db/Dockerfile.setup",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "1.5Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "tz": "America/Vancouver",
            "volumeCapacity": "500Mi",
            "cpuRequest": "50m",
            "cpuLimit": "400m",
            "memoryRequest": "100Mi",
            "memoryLimit": "2Gi",
            "replicas": "1"
          }
        },
        "dev": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "sourceContextDir": "database",
            "dbSetupDockerfilePath": "./.docker/db/Dockerfile.setup",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "1.5Gi"
          },
          "deploy": {
            "namespace": "af2668-dev",
            "nodeEnv": "development",
            "tz": "America/Vancouver",
            "volumeCapacity": "3Gi",
            "cpuRequest": "50m",
            "cpuLimit": "400m",
            "memoryRequest": "100Mi",
            "memoryLimit": "2Gi",
            "replicas": "1"
          }
        },
        "test": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "sourceContextDir": "database",
            "dbSetupDockerfilePath": "./.docker/db/Dockerfile.migrate",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "1.5Gi"
          },
          "deploy": {
            "namespace": "af2668-test",
            "nodeEnv": "production",
            "tz": "America/Vancouver",
            "volumeCapacity": "3Gi",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi",
            "replicas": "1"
          }
        },
        "prod": {
          "build": {
            "namespace": "af2668-tools",
            "tz": "America/Vancouver",
            "sourceContextDir": "database",
            "dbSetupDockerfilePath": "./.docker/db/Dockerfile.migrate",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "1.5Gi"
          },
          "deploy": {
            "namespace": "af2668-prod",
            "nodeEnv": "production",
            "tz": "America/Vancouver",
            "volumeCapacity": "5Gi",
            "cpuRequest": "50m",
            "cpuLimit": "1000m",
            "memoryRequest": "100Mi",
            "memoryLimit": "3Gi",
            "replicas": "1"
          }
        }
      },
      "sso": {
        "pr": {
          "host": "https://dev.loginproxy.gov.bc.ca/auth",
          "realm": "standard",
          "clientId": "sims-4461",
          "keycloakSecret": "keycloak",
          "serviceClient": {
            "serviceClientName": "sims-svc-4464",
            "keycloakSecretServiceClientPasswordKey": "sims_svc_client_password"
          },
          "cssApi": {
            "cssApiTokenUrl": "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token",
            "cssApiClientId": "service-account-team-1190-4229",
            "cssApiHost": "https://api.loginproxy.gov.bc.ca/api/v1",
            "keycloakSecretCssApiSecretKey": "css_api_client_secret",
            "cssApiEnvironment": "dev"
          }
        },
        "dev": {
          "host": "https://dev.loginproxy.gov.bc.ca/auth",
          "realm": "standard",
          "clientId": "sims-4461",
          "keycloakSecret": "keycloak",
          "serviceClient": {
            "serviceClientName": "sims-svc-4464",
            "keycloakSecretServiceClientPasswordKey": "sims_svc_client_password"
          },
          "cssApi": {
            "cssApiTokenUrl": "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token",
            "cssApiClientId": "service-account-team-1190-4229",
            "cssApiHost": "https://api.loginproxy.gov.bc.ca/api/v1",
            "keycloakSecretCssApiSecretKey": "css_api_client_secret",
            "cssApiEnvironment": "dev"
          }
        },
        "test": {
          "host": "https://test.loginproxy.gov.bc.ca/auth",
          "realm": "standard",
          "clientId": "sims-4461",
          "keycloakSecret": "keycloak",
          "serviceClient": {
            "serviceClientName": "sims-svc-4464",
            "keycloakSecretServiceClientPasswordKey": "sims_svc_client_password"
          },
          "cssApi": {
            "cssApiTokenUrl": "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token",
            "cssApiClientId": "service-account-team-1190-4229",
            "cssApiHost": "https://api.loginproxy.gov.bc.ca/api/v1",
            "keycloakSecretCssApiSecretKey": "css_api_client_secret",
            "cssApiEnvironment": "test"
          }
        },
        "prod": {
          "host": "https://loginproxy.gov.bc.ca/auth",
          "realm": "standard",
          "clientId": "sims-4461",
          "keycloakSecret": "keycloak",
          "serviceClient": {
            "serviceClientName": "sims-svc-4464",
            "keycloakSecretServiceClientPasswordKey": "sims_svc_client_password"
          },
          "cssApi": {
            "cssApiTokenUrl": "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token",
            "cssApiClientId": "service-account-team-1190-4229",
            "cssApiHost": "https://api.loginproxy.gov.bc.ca/api/v1",
            "keycloakSecretCssApiSecretKey": "css_api_client_secret",
            "cssApiEnvironment": "prod"
          }
        }
      }
    }
