# Test environment values for SIMS
environment:
  name: test
  id: deploy

# Database configuration
app:
  nodeEnv: production # This is set to production as test is not a valid name in the Knexfile

# Openshift Resources
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 2000m
    memory: 5Gi

# Volume for persistent data
persistence:
  existingClaim: "biohubbc-db-postgresql-test"