-- populate_summary_parameter_method_code.sql

insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('OTC','Observed - Total Count','The parameter value is the number of observations during a total count Survey. Total counts are intended to enumerate all individuals (or their sign) in a Study Area using complete coverage of the Study Area. For example, alpine areas are usually small, and thus 100% flight coverage is practical for surveying mountain sheep and goats, and sometimes caribou. (RISC 20XX)', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('OSC','Observed - Sample-based Count','The parameter value is the number of observations during a sample-based Survey. Sample-based Surveys are required wherever it is impractical to survey the entire Study Area. In sample-based Surveys, a portion of the Study Area is counted within defined sample units (e.g., quadrats or blocks). The results are then used to estimate animal abundance throughout the Study Area. A sample-based Survey count should typically be accompanied by a modeled or corrected estimated count. (RISC 20XX)', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MNKA','Minimum Number Known Alive','The value is based on the sampled value but is adjusted using additional information other than a model or SCF. The adjusted value represents the minimum number of individuals known to be alive in the area of interest. Examples of situations in which MNKA may be used are: (1) observed count is adjusted based on pre- or post-survey information. (2) a Survey uses telemetry to locate additional collared individuals outside of the defined study area.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('EK','Expert Knowledge','The parameter value is an expert''s knowledge, which is based on knowledge of survey conditions, surveyor experience, scientific opinion, and other survey data.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC','Model or Correction','The parameter value is based on the sampled value (i.e. based on the observations or detections) but is adjusted via a model (e.g., Moosepop, Aerial Survey) and/or statistical calculation and/or sightability correction factor and/or detectability correction factor. The adjusted value represents an estimate of the true parameter value for the Study Area or Design Component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC-JHE','Model or Correction - Joint Hypergeometric Estimator','The parameter value is based on the sampled value (i.e. based on the observations or detections) but is adjusted via the Joint Hypergeometric Estimator. The adjusted value represents an estimate of the true parameter value for the Study Area or Design Component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC-LP','Model or Correction - Lincoln-Peterson','The parameter value is based on the sampled value (i.e. based on the observations or detections) but is adjusted via Lincoln-Peterson formula. The adjusted value represents an estimate of the true parameter value for the Study Area or Design Component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC-MP','Model or Correction - MoosePop','The parameter value is based on the sampled value (i.e. based on the observations or detections) but is adjusted via the MoosePop model. The adjusted value represents an estimate of the true parameter value for the Study Area or Design Component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC-RM','Model or Correction - Recruitment-Mortality','The parameter value is based on the sampled value (i.e. based on the observations or detections) but is adjusted using the recruitment-mortality equation. The adjusted value represents an estimate of the true parameter value for the study area or design component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('MC-EK','Model or Correction & Expert Knowledge','The parameter value is based on the modelled or corrected  value but is adjusted via expert knowledge. The adjusted value represents an estimate of the true parameter value for the study area or design component of interest.', now());
insert into summary_parameter_method_code (code, name, description, record_effective_date) values ('DC','Described in Comments','The parameter method is described in comments. Note: Describing the data in comments rather than using a predefined code may reduce the clarity and accessibility of data.', now());
