# Default values for app chart
environment:
  licensePlate: "af2668" # License plate of the project
  name: "" # Environment name (dev, test, prod)
  id: "" # Environment id (PR, deploy)
  ts: "" # Timestamp of the deployment
  
image:
  registry: "image-registry.openshift-image-registry.svc:5000" # The base image registry URL
  image: af2668-tools/biohubbc-app # Always pull from tools namespace

# App configuration
app:
  name: biohubbc-app
  nodeEnv: "" # NODE_ENV specification variable
  apiHost: "" # API host for application backend
  featureFlags: "" # Used to identify features that should be temporarily disabled/hidden. Must be a comma delimited list of keywords.

  # BioHub Platform (aka: Backbone)
  backbonePublicApiHost: "" # Backbone API host for application frontend
  backbonePublicWebHost: "" # Backbone web app host for "View in BioHub" links (e.g. submission pages)
  biohubTaxonPath: /api/taxonomy/taxon # API path for BioHub Platform Backbone taxon endpoint. Example "/api/path/to/taxon"
  biohubTaxonTsnPath: /api/taxonomy/taxon/tsn # API path for BioHub Platform Backbone taxon TSN endpoint. Example "/api/path/to/taxon/tsn"

  # Siteminder
  siteminderLogoutURL: "" # Siteminder URL to log out and clear the session for the logged in user

  # Keycloak
  keycloak:
    host: "" # Keycloak login url
    realm: standard # Realm identifier or name
    clientId: sims-4461 # Client Id for application

  # Object Store (S3)
  objectStore:
    secretName: biohubbc-object-store # Secrets used to read and write to the S3 storage

  # Request limits
  requestLimits:
    uploadNumFiles: 10 # Default maximum number of files that can be uploaded at a time vai the upload component UI.
    uploadFileSize: "52428800" # Default maximum size of a single file that can be uploaded by the upload component UI.
  
  
# Openshift Resources
replicas: ""
resources:
  requests:
    cpu: ""
    memory: ""
  limits:
    cpu: ""
    memory: ""

# Service configuration
service:
  type: ClusterIP
  name: 7100-tcp
  port: 7100
  targetPort: 7100

# Route configuration (OpenShift)
route:
  host: ""