import { IDBConnection } from '../database/db';
import {
  getClimateChangeInitiativeSQL,
  getFundingAgencySQL,
  getLandBasedInvestmentStrategySQL,
  getManagementActionTypeSQL
} from '../queries/code-queries';
import { getLogger } from '../utils/logger';

const defaultLog = getLogger('queries/code-queries');

export interface IAllCodeSets {
  management_action_type: object;
  climate_change_initiative: object;
  land_based_investment_strategy: object;
  funding_agency: object;
  species: object;
}

/**
 * Function that fetches all code sets.
 *
 * @param {PoolClient} connection
 * @returns {IAllCodeSets} an object containing all code sets
 */
export async function getAllCodeSets(connection: IDBConnection): Promise<IAllCodeSets | null> {
  defaultLog.debug({ message: 'getAllCodeSets' });

  if (!connection) {
    return null;
  }

  await connection.open();

  const [
    management_action_type,
    climate_change_initiative,
    land_based_investment_strategy,
    funding_agency
  ] = await Promise.all([
    await connection.query(getManagementActionTypeSQL().text),
    await connection.query(getClimateChangeInitiativeSQL().text),
    await connection.query(getLandBasedInvestmentStrategySQL().text),
    await connection.query(getFundingAgencySQL().text)
  ]);

  await connection.commit();

  connection.release();

  const result: IAllCodeSets = {
    management_action_type: (management_action_type && management_action_type.rows) || [],
    climate_change_initiative: (climate_change_initiative && climate_change_initiative.rows) || [],
    land_based_investment_strategy: (land_based_investment_strategy && land_based_investment_strategy.rows) || [],
    funding_agency: (funding_agency && funding_agency.rows) || [],
    // TODO Temporarily hard coded list of basic species values for demo purposes
    species: [
      { id: 1, description: 'Acuteleaf Small Limestone Moss [Seligeria acutifolia]' },
      { id: 1, description: 'Alkaline Wing-nerved Moss [Pterygoneurum kozlovii]' },
      { id: 1, description: 'American Badger [Taxidea taxus]' },
      { id: 1, description: 'American Badger jeffersonii subspecies [Taxidea taxus  jeffersonii]' },
      { id: 1, description: 'American Black Bear [Ursus americanus]' },
      { id: 1, description: 'American Coot [Fulica americana]' },
      { id: 1, description: 'American White Pelican [Pelecanus erythrorhynchos]' },
      { id: 1, description: 'Ancient Murrelet [Synthliboramphus antiquus]' },
      { id: 1, description: 'Audouin’s Night-stalking Tiger Beetle [Omus audouini]' },
      { id: 1, description: 'Bald Eagle [Haliaeetus leucocephalus]' },
      { id: 1, description: 'Band-tailed Pigeon [Patagioenas fasciata]' },
      { id: 1, description: 'Banded Cord-moss [Entosthodon fascicularis]' },
      { id: 1, description: 'Bank Swallow [Riparia riparia]' },
      { id: 1, description: 'Barn Owl [Tyto alba]' },
      { id: 1, description: 'Barn Swallow [Hirundo rustica]' },
      { id: 1, description: 'Basking Shark [Cetorhinus maximus]' },
      { id: 1, description: 'Batwing Vinyl Lichen [Leptogium platynum]' },
      { id: 1, description: "Bear's-foot Sanicle [Sanicula arctopoides]" },
      { id: 1, description: 'Bearded Owl-clover [Triphysaria versicolor]' },
      { id: 1, description: "Behr's Hairstreak [Satyrium behrii]" },
      { id: 1, description: 'Bent Spike-rush [Eleocharis geniculata]' },
      { id: 1, description: 'Black Swift [Cypseloides niger]' },
      { id: 1, description: 'Black Tern [Chlidonias niger]' },
      { id: 1, description: 'Blue Shark [Prionace glauca]' },
      { id: 1, description: 'Blue-grey Taildropper [Prophysaon coeruleum]' },
      { id: 1, description: 'Bobolink [Dolichonyx oryzivorus]' },
      { id: 1, description: 'Bog Bird’s-foot Trefoil [Lotus pinnatus]' },
      { id: 1, description: 'Boreal Owl [Aegolius funereus]' },
      { id: 1, description: 'Branched Phacelia [Phacelia ramosissima]' },
      { id: 1, description: 'Brook Spike-primrose [Epilobium torreyi]' },
      { id: 1, description: 'Buff-breasted Sandpiper [Tryngites subruficollis]' },
      { id: 1, description: 'Bull Trout [Salvelinus confluentus]' },
      { id: 1, description: 'Burrowing Owl [Athene cunicularia]' },
      { id: 1, description: 'California Buttercup [Ranunculus californicus]' },
      { id: 1, description: 'California Sea Lion [Zalophus californianus]' },
      { id: 1, description: 'Canada Lynx [Lynx canadensis]' },
      { id: 1, description: 'Canada Warbler [Cardellina canadensis]' },
      { id: 1, description: 'Canyon Wren [Catherpes mexicanus]' },
      { id: 1, description: 'Carey’s Small Limestone Moss [Seligeria careyana]' },
      { id: 1, description: 'Caribou dawsoni subspecies [Rangifer tarandus  dawsoni]' },
      { id: 1, description: 'Caribou [Rangifer tarandus]' },
      { id: 1, description: 'Cascade Mantled Ground Squirrel [Spermophilus saturatus]' },
      { id: 1, description: 'Caspian Tern [Sterna caspia]' },
      { id: 1, description: "Cassin's Auklet [Ptychoramphus aleuticus]" },
      { id: 1, description: 'Chinook Salmon [Oncorhynchus tshawytscha]' },
      { id: 1, description: 'Chiselmouth [Acrocheilus alutaceus]' },
      { id: 1, description: 'Cliff Paintbrush [Castilleja rupicola]' },
      { id: 1, description: 'Coast Manroot [Marah oregana]' },
      { id: 1, description: 'Coast Microseris [Microseris bigelovii]' },
      { id: 1, description: 'Coastal Giant Salamander [Dicamptodon tenebrosus]' },
      { id: 1, description: "Coastal Scouler's Catchfly [Silene scouleri  ssp. grandis]" },
      { id: 1, description: 'Coastal Tailed Frog [Ascaphus truei]' },
      { id: 1, description: 'Coastal Wood Fern [Dryopteris arguta]' },
      { id: 1, description: 'Coastrange Sculpin [Cottus aleuticus]' },
      { id: 1, description: "Coeur d'Alene Salamander [Plethodon idahoensis]" },
      { id: 1, description: 'Coho Salmon [Oncorhynchus kisutch]' },
      { id: 1, description: 'Collared Pika [Ochotona collaris]' },
      { id: 1, description: 'Columbia Dune Moth [Copablepharon absidum]' },
      { id: 1, description: 'Columbia Quillwort [Isoetes minima]' },
      { id: 1, description: 'Columbia Sculpin [Cottus hubbsi]' },
      { id: 1, description: 'Columbia Spotted Frog [Rana luteiventris]' },
      { id: 1, description: 'Columbian Carpet Moss [Bryoerythrophyllum columbianum]' },
      { id: 1, description: 'Common Loon [Gavia immer]' },
      { id: 1, description: 'Common Nighthawk [Chordeiles minor]' },
      { id: 1, description: 'Common Poorwill [Phalaenoptilus nuttallii]' },
      { id: 1, description: 'Contorted-pod Evening-primrose [Camissonia contorta]' },
      { id: 1, description: "Cooper's Hawk [Accipiter cooperii]" },
      { id: 1, description: 'Crumpled Tarpaper Lichen [Collema coniophilum]' },
      { id: 1, description: 'Cryptic Paw Lichen [Nephroma occultum]' },
      { id: 1, description: 'Dalton’s Moss [Daltonia splachnoides]' },
      { id: 1, description: 'Deltoid Balsamroot [Balsamorhiza deltoidea]' },
      { id: 1, description: 'Dense Spike-primrose [Epilobium densiflorum]' },
      { id: 1, description: 'Dense-flowered Lupine [Lupinus densiflorus]' },
      { id: 1, description: 'Desert Nightsnake [Hypsiglena chlorophaea]' },
      { id: 1, description: 'Double-crested Cormorant [Phalacrocorax auritus]' },
      { id: 1, description: 'Dromedary Jumping-slug [Hemphillia dromedarius]' },
      { id: 1, description: 'Drooping-leaved Beard-moss [Oxystegus recurvifolius]' },
      { id: 1, description: 'Dun Skipper vestris subspecies [Euphyes vestris  vestris]' },
      { id: 1, description: 'Dwarf Hesperochiron [Hesperochiron pumilus]' },
      { id: 1, description: 'Dwarf Sandwort [Minuartia pusilla]' },
      { id: 1, description: 'Dwarf Woolly-heads [Psilocarphus brevissimus]' },
      { id: 1, description: "Edwards' Beach Moth [Anarta edwardsii]" },
      { id: 1, description: 'Enos Lake Benthic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Enos Lake Limnetic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Enos Lake Threespine Sticklebacks [Gasterosteus spp.]' },
      { id: 1, description: 'Ensatina [Ensatina eschscholtzii]' },
      { id: 1, description: 'Ermine haidarum subspecies [Mustela erminea  haidarum]' },
      { id: 1, description: 'Eulachon [Thaleichthys pacificus]' },
      { id: 1, description: 'Evening Fieldslug [Deroceras hesperium]' },
      { id: 1, description: 'Evening Grosbeak [Coccothraustes vespertinus]' },
      { id: 1, description: 'Fameflower [Talinum sediforme]' },
      { id: 1, description: 'Flammulated Owl [Otus flammeolus]' },
      { id: 1, description: 'Foothill Sedge [Carex tumulicola]' },
      { id: 1, description: "Forster's Tern [Sterna forsteri]" },
      { id: 1, description: 'Fragrant Popcornflower [Plagiobothrys figuratus]' },
      { id: 1, description: 'Fringed Bat [Myotis thysanodes]' },
      { id: 1, description: 'Frosted Glass-whiskers [Sclerophora peronella]' },
      { id: 1, description: 'Georgia Basin Bog Spider [Gnaphosa snohomish]' },
      { id: 1, description: 'Giant Helleborine [Epipactis gigantea]' },
      { id: 1, description: 'Giant Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Golden Eagle [Aquila chrysaetos]' },
      { id: 1, description: 'Golden Paintbrush [Castilleja levisecta]' },
      { id: 1, description: 'Grand Coulee Owl-clover [Orthocarpus barbatus]' },
      { id: 1, description: "Gray's Desert-parsley [Lomatium grayi]" },
      { id: 1, description: 'Great Basin Gophersnake [Pituophis catenifer  deserticola]' },
      { id: 1, description: 'Great Basin Spadefoot [Spea intermontana]' },
      { id: 1, description: 'Great Blue Heron fannini subspecies [Ardea herodias  fannini]' },
      { id: 1, description: 'Great Grey Owl [Strix nebulosa]' },
      { id: 1, description: 'Greater Sage-Grouse phaios subspecies [Centrocercus urophasianus  phaios]' },
      { id: 1, description: 'Green Sturgeon [Acipenser medirostris]' },
      { id: 1, description: 'Grey Flycatcher [Empidonax wrightii]' },
      { id: 1, description: 'Grey Whale [Eschrichtius robustus]' },
      { id: 1, description: 'Grizzly Bear [Ursus arctos]' },
      { id: 1, description: 'Gypsy Cuckoo Bumble Bee [Bombus bohemicus]' },
      { id: 1, description: 'Gyrfalcon [Falco rusticolus]' },
      { id: 1, description: 'Hadley Lake Benthic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Hadley Lake Limnetic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Haida Gwaii Slug [Staala gwaii]' },
      { id: 1, description: 'Hairy Paintbrush [Castilleja tenuis]' },
      { id: 1, description: 'Half-moon Hairstreak [Satyrium semiluna]' },
      { id: 1, description: "Haller's Apple Moss [Bartramia halleriana]" },
      { id: 1, description: 'Harbour Porpoise [Phocoena phocoena  vomerina]' },
      { id: 1, description: 'Harbour Seal Pacific subspecies [Phoca vitulina  richardsi]' },
      { id: 1, description: 'Horned Grebe [Podiceps auritus]' },
      { id: 1, description: 'Streaked Horned Lark [Eremophila alpestris  strigata]' },
      { id: 1, description: 'Hotwater Physa [Physella wrighti]' },
      { id: 1, description: "Howell's Triteleia [Triteleia howellii]" },
      { id: 1, description: 'Hudsonian Godwit [Limosa haemastica]' },
      { id: 1, description: 'Island Blue [Plebejus saepiolus  insulanus]' },
      { id: 1, description: 'Island Marble [Euchloe ausonides  insulanus]' },
      { id: 1, description: 'Island Tiger Moth [Grammia complicata]' },
      { id: 1, description: "Keen's Long-eared Bat [Myotis keenii]" },
      { id: 1, description: "Kellogg's Rush [Juncus kelloggii]" },
      { id: 1, description: 'Lake Chub [Couesius plumbeus]' },
      { id: 1, description: 'Large-flowered Brickellia [Brickellia grandiflora]' },
      { id: 1, description: "Leiberg's Fleabane [Erigeron leibergii]" },
      { id: 1, description: "Lemmon's Holly Fern [Polystichum lemmonii]" },
      { id: 1, description: 'Leopard Dace [Rhinichthys falcatus]' },
      { id: 1, description: 'Lesser Yellowlegs [Tringa flavipes]' },
      { id: 1, description: "Lewis's Woodpecker [Melanerpes lewis]" },
      { id: 1, description: 'Limber Pine [Pinus flexilis]' },
      { id: 1, description: "Lindley's False Silverpuffs [Uropappus lindleyi]" },
      { id: 1, description: 'Little Brown Myotis [Myotis lucifugus]' },
      { id: 1, description: 'Little Quarry Lake Benthic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Little Quarry Lake Limnetic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Loggerhead Shrike [Lanius ludovicianus]' },
      { id: 1, description: 'Long-billed Curlew [Numenius americanus]' },
      { id: 1, description: 'Long-toed Salamander [Ambystoma macrodactylum]' },
      { id: 1, description: 'Longfin Smelt [Spirinchus thaleichthys]' },
      { id: 1, description: "Lyall's Mariposa Lily [Calochortus lyallii]" },
      { id: 1, description: "Macoun's Meadowfoam [Limnanthes macounii]" },
      { id: 1, description: 'Magnum Mantleslug [Magnipelta mycophaga]' },
      { id: 1, description: 'Marbled Murrelet [Brachyramphus marmoratus]' },
      { id: 1, description: 'Margined Streamside Moss [Scouleria marginata]' },
      { id: 1, description: 'Merlin [Falco columbarius]' },
      { id: 1, description: 'Mexican Mosquito-fern [Azolla mexicana]' },
      { id: 1, description: 'Misty Lake Lentic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Misty Lake Lotic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Monarch [Danaus plexippus]' },
      { id: 1, description: 'Mormon Metalmark [Apodemia mormo]' },
      { id: 1, description: 'Mountain Beaver [Aplodontia rufa]' },
      { id: 1, description: 'Mountain Crab-eye [Acroscyphus sphaerophoroides]' },
      { id: 1, description: 'Mountain Holly Fern [Polystichum scopulinum]' },
      { id: 1, description: 'Mountain Sucker [Catostomus platyrhynchus]' },
      { id: 1, description: "Muhlenberg's Centaury [Centaurium muehlenbergii]" },
      { id: 1, description: "Nelson's Sharp-tailed Sparrow [Ammodramus nelsoni]" },
      { id: 1, description: 'Nine-spotted Lady Beetle [Coccinella novemnotata]' },
      { id: 1, description: 'Nooksack Dace [Rhinichthys cataractae]' },
      { id: 1, description: 'Northern Abalone [Haliotis kamtschatkana]' },
      { id: 1, description: 'Northern Alligator Lizard [Elgaria coerulea]' },
      { id: 1, description: 'Northern Elephant Seal [Mirounga angustirostris]' },
      { id: 1, description: 'Northern Fur Seal [Callorhinus ursinus]' },
      { id: 1, description: 'Northern Goshawk atricapillus subspecies [Accipiter gentilis  atricapillus]' },
      { id: 1, description: 'Northern Goshawk laingi subspecies [Accipiter gentilis  laingi]' },
      { id: 1, description: 'Northern Grey Wolf [Canis lupus  occidentalis]' },
      { id: 1, description: 'Northern Harrier [Circus cyaneus]' },
      { id: 1, description: 'Northern Hawk Owl [Surnia ulula]' },
      { id: 1, description: 'Northern Leopard Frog [Lithobates pipiens]' },
      { id: 1, description: 'Northern Myotis [Myotis septentrionalis]' },
      { id: 1, description: 'Northern Saw-whet Owl brooksi subspecies [Aegolius acadicus  brooksi]' },
      { id: 1, description: 'Northwestern Cellar Spider [Psilochorus hesperus]' },
      { id: 1, description: 'Northwestern Gartersnake [Thamnophis ordinoides]' },
      { id: 1, description: 'Northwestern Salamander [Ambystoma gracile]' },
      { id: 1, description: 'Nugget Moss [Microbryum vlassovii]' },
      { id: 1, description: "Nuttall's Cottontail nuttallii subspecies [Sylvilagus nuttallii  nuttallii]" },
      { id: 1, description: "Nuttall's Sheep Moth [Hemileuca nuttalli]" },
      { id: 1, description: 'Okanagan Efferia [Efferia okanagana]' },
      { id: 1, description: 'Okanogan Stickseed [Hackelia ciliata]' },
      { id: 1, description: 'Oldgrowth Specklebelly Lichen [Pseudocyphellaria rainierensis]' },
      { id: 1, description: 'Olive Clubtail [Stylurus olivaceus]' },
      { id: 1, description: 'Olive-sided Flycatcher [Contopus cooperi]' },
      { id: 1, description: 'Olympia Oyster [Ostrea lurida]' },
      { id: 1, description: 'Oregon Branded Skipper [Hesperia colorado  oregonia]' },
      { id: 1, description: 'Oregon Forestsnail [Allogona townsendiana]' },
      { id: 1, description: 'Oregon Lupine [Lupinus oreganus]' },
      { id: 1, description: 'Oregon Spotted Frog [Rana pretiosa]' },
      { id: 1, description: 'Pacific Gophersnake [Pituophis catenifer  catenifer]' },
      { id: 1, description: 'Pacific Pond Turtle [Actinemys marmorata]' },
      { id: 1, description: 'Pacific Rhododendron [Rhododendron macrophyllum]' },
      { id: 1, description: 'Pacific Water Shrew [Sorex bendirii]' },
      { id: 1, description: 'Pallid Bat [Antrozous pallidus]' },
      { id: 1, description: 'Paxton Lake Benthic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Paxton Lake Limnetic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Peacock Vinyl Lichen [Leptogium polycarpum]' },
      { id: 1, description: 'Peregrine Falcon anatum subspecies [Falco peregrinus  anatum]' },
      { id: 1, description: 'Peregrine Falcon anatum/tundrius [Falco peregrinus  anatum/tundrius]' },
      { id: 1, description: 'Peregrine Falcon pealei subspecies [Falco peregrinus  pealei]' },
      { id: 1, description: 'Phantom Orchid [Cephalanthera austiniae]' },
      { id: 1, description: 'Pink Sand-verbena [Abronia umbellata]' },
      { id: 1, description: 'Pink-footed Shearwater [Ardenna creatopus]' },
      { id: 1, description: 'Pixie Poacher [Occella impi]' },
      { id: 1, description: 'Plains Bison [Bison bison  bison]' },
      { id: 1, description: 'Poor Pocket Moss [Fissidens pauperculus]' },
      { id: 1, description: "Porsild's Bryum [Haplodontium macrocarpum]" },
      { id: 1, description: 'Prairie Falcon [Falco mexicanus]' },
      { id: 1, description: 'Prairie Lupine [Lupinus lepidus]' },
      { id: 1, description: 'Purple Sanicle [Sanicula bipinnatifida]' },
      { id: 1, description: 'Purple Spikerush [Eleocharis atropurpurea]' },
      { id: 1, description: 'Pygmy Pocket Moss [Fissidens exilis]' },
      { id: 1, description: 'Pygmy Short-horned Lizard [Phrynosoma douglasii]' },
      { id: 1, description: 'Pygmy Slug [Kootenaia burkei]' },
      { id: 1, description: 'Pygmy Whitefish [Prosopium coulterii]' },
      { id: 1, description: 'Rabbit-brush Goldenweed [Ericameria bloomeri]' },
      { id: 1, description: 'Rayless Goldfields [Lasthenia glaberrima]' },
      { id: 1, description: 'Red Knot roselaari subspecies [Calidris canutus  roselaari]' },
      { id: 1, description: 'Red Knot roselaari type [Calidris canutus  roselaari]' },
      { id: 1, description: 'Northern Red-legged Frog [Rana aurora]' },
      { id: 1, description: 'Red-necked Grebe [Podiceps grisegena]' },
      { id: 1, description: 'Red-necked Phalarope [Phalaropus lobatus]' },
      { id: 1, description: 'Red-tailed Hawk [Buteo jamaicensis]' },
      { id: 1, description: 'Rigid Apple Moss [Bartramia aprica]' },
      { id: 1, description: 'Rocky Mountain Capshell [Acroloxus coloradensis]' },
      { id: 1, description: 'Rocky Mountain Ridged Mussel [Gonidea angulata]' },
      { id: 1, description: 'Rocky Mountain Sculpin [Cottus  sp.]' },
      { id: 1, description: 'Rocky Mountain Tailed Frog [Ascaphus montanus]' },
      { id: 1, description: "Roell's Brotherella Moss [Brotherella roellii]" },
      { id: 1, description: 'Rosy Owl-clover [Orthocarpus bracteosus]' },
      { id: 1, description: 'Rough-legged Hawk [Buteo lagopus]' },
      { id: 1, description: 'Northern Rubber Boa [Charina bottae]' },
      { id: 1, description: 'Rusty Blackbird [Euphagus carolinus]' },
      { id: 1, description: 'Rusty Cord-moss [Entosthodon rubiginosus]' },
      { id: 1, description: 'Sage Thrasher [Oreoscoptes montanus]' },
      { id: 1, description: 'Salish Sucker [Catostomus sp. cf. catostomus]' },
      { id: 1, description: 'Sand-verbena Moth [Copablepharon fuscum]' },
      { id: 1, description: 'Sandhill Crane tabida subspecies [Grus canadensis  tabida]' },
      { id: 1, description: 'Scarlet Ammannia [Ammannia robusta]' },
      { id: 1, description: "Schleicher's Silk Moss [Entodon schleicheri]" },
      { id: 1, description: "Scouler's Corydalis [Corydalis scouleri]" },
      { id: 1, description: 'Sea Otter [Enhydra lutris]' },
      { id: 1, description: 'Seaside Birds-foot Lotus [Lotus formosissimus]' },
      { id: 1, description: 'Seaside Bone Lichen [Hypogymnia heterophylla]' },
      { id: 1, description: 'Seaside Centipede Lichen [Heterodermia sitchensis]' },
      { id: 1, description: 'Sharp-shinned Hawk [Accipiter striatus]' },
      { id: 1, description: 'Sharp-tailed Snake [Contia tenuis]' },
      { id: 1, description: 'Sheathed Slug [Zacoleus idahoensis]' },
      { id: 1, description: 'Short-eared Owl [Asio flammeus]' },
      { id: 1, description: 'Short-rayed Alkali Aster [Symphyotrichum frondosum]' },
      { id: 1, description: 'Short-tailed Albatross [Phoebastria albatrus]' },
      { id: 1, description: 'Shortface Lanx [Fisherola nuttallii]' },
      { id: 1, description: 'Shorthead Sculpin [Cottus confusus]' },
      { id: 1, description: 'Showy Phlox [Phlox speciosa  ssp. occidentalis]' },
      { id: 1, description: 'Silky Beach Pea [Lathyrus littoralis]' },
      { id: 1, description: 'Silver Hair Moss [Fabronia pusilla]' },
      { id: 1, description: 'Slender Collomia [Collomia tenella]' },
      { id: 1, description: 'Slender Popcornflower [Plagiobothrys tenellus]' },
      { id: 1, description: 'Slender Woolly-heads [Psilocarphus tenellus  var. tenellus]' },
      { id: 1, description: 'Slender Yoke-moss [Zygodon gracilis]' },
      { id: 1, description: 'Small-flowered Lipocarpha [Lipocarpha micrantha]' },
      { id: 1, description: 'Small-flowered Tonella [Tonella tenella]' },
      { id: 1, description: 'Smoker’s Lung Lichen [Lobaria retigera]' },
      { id: 1, description: 'Puget Oregonian [Cryptomastix devia]' },
      { id: 1, description: 'Sockeye Salmon [Oncorhynchus nerka]' },
      { id: 1, description: 'Sonora Skipper [Polites sonora]' },
      { id: 1, description: 'Southern Grey Wolf [Canis lupus  nubilus]' },
      { id: 1, description: 'Southern Maidenhair Fern [Adiantum capillus-veneris]' },
      { id: 1, description: "Spalding's Campion [Silene spaldingii]" },
      { id: 1, description: 'Speckled Dace [Rhinichthys osculus]' },
      { id: 1, description: 'Spoonhead Sculpin [Cottus ricei]' },
      { id: 1, description: 'Spotted Bat [Euderma maculatum]' },
      { id: 1, description: 'Spotted Owl caurina subspecies [Strix occidentalis  caurina]' },
      { id: 1, description: 'Steelhead Trout [Oncorhynchus mykiss]' },
      { id: 1, description: 'Steller Sea Lion [Eumetopias jubatus]' },
      { id: 1, description: 'Stoloniferous Pussytoes [Antennaria flagellaris]' },
      { id: 1, description: 'Streambank Lupine [Lupinus rivularis]' },
      { id: 1, description: 'Suckley’s Cuckoo Bumble Bee [Bombus suckleyi]' },
      { id: 1, description: 'Tall Bugbane [Actaea elata]' },
      { id: 1, description: 'Tall Woolly-heads [Psilocarphus elatior]' },
      { id: 1, description: "Taylor's Checkerspot [Euphydryas editha  taylori]" },
      { id: 1, description: 'Threaded Vertigo [Nearctula  sp.]' },
      { id: 1, description: 'Tiger Salamander [Ambystoma tigrinum]' },
      { id: 1, description: 'Tiny Tassel [Crossidium seriatum]' },
      { id: 1, description: 'Toothcup [Rotala ramosior]' },
      { id: 1, description: "Townsend's Mole [Scapanus townsendii]" },
      { id: 1, description: 'Transverse Lady Beetle [Coccinella transversoguttata]' },
      { id: 1, description: 'Trumpeter Swan [Cygnus buccinator]' },
      { id: 1, description: "Tweedy's Lewisia [Lewisiopsis tweedyi]" },
      { id: 1, description: 'Twisted Oak Moss [Syntrichia laevipila]' },
      { id: 1, description: 'Umatilla Dace [Rhinichthys umatilla]' },
      { id: 1, description: 'Unarmoured Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Ute Ladies’–tresses [Spiranthes diluvialis]' },
      { id: 1, description: 'Vananda Creek Benthic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Vananda Creek Limnetic Threespine Stickleback [Gasterosteus aculeatus]' },
      { id: 1, description: 'Vancouver Island Beggarticks [Bidens amplissima]' },
      { id: 1, description: 'Vancouver Island Marmot [Marmota vancouverensis]' },
      { id: 1, description: 'Vancouver Lamprey [Entosphenus macrostomus]' },
      { id: 1, description: 'Coastal Vesper Sparrow [Pooecetes gramineus  affinis]' },
      { id: 1, description: "Victoria's Owl-clover [Castilleja victoriae]" },
      { id: 1, description: 'Vivid Dancer [Argia vivida]' },
      { id: 1, description: "Wallis' Dark Saltflat Tiger Beetle [Cicindela parowana  wallisi]" },
      { id: 1, description: 'Wandering Salamander [Aneides vagrans]' },
      { id: 1, description: 'Warty Jumping-slug [Hemphillia glandulosa]' },
      { id: 1, description: 'Water-plantain Buttercup [Ranunculus alismifolius]' },
      { id: 1, description: 'Western Banded Tigersnail [Anguispira kochi  occidentalis]' },
      { id: 1, description: 'Western Brook Lamprey [Lampetra richardsoni]' },
      { id: 1, description: 'Western Bumble Bee mckayi subspecies [Bombus occidentalis  mckayi]' },
      { id: 1, description: 'Western Bumble Bee occidentalis subspecies [Bombus occidentalis  occidentalis]' },
      { id: 1, description: 'Western Grebe [Aechmophorus occidentalis]' },
      { id: 1, description: 'Western Harvest Mouse megalotis subspecies [Reithrodontomys megalotis  megalotis]' },
      { id: 1, description: 'Western Painted Turtle [Chrysemys picta  bellii]' },
      { id: 1, description: 'Western Rattlesnake [Crotalus oreganus]' },
      { id: 1, description: 'Western Red-backed Salamander [Plethodon vehiculum]' },
      { id: 1, description: 'Western Screech-owl [Megascops kennicottii]' },
      { id: 1, description: 'Western Screech-owl kennicottii subspecies [Megascops kennicottii  kennicottii]' },
      { id: 1, description: 'Western Screech-owl macfarlanei subspecies [Megascops kennicottii  macfarlanei]' },
      { id: 1, description: 'Western Skink [Plestiodon skiltonianus]' },
      { id: 1, description: 'Western Tiger Salamander [Ambystoma mavortium]' },
      { id: 1, description: 'Western Toad [Anaxyrus boreas]' },
      { id: 1, description: 'Western Waterfan [Peltigera gowardii]' },
      { id: 1, description: 'Western Yellow-bellied Racer [Coluber constrictor  mormon]' },
      { id: 1, description: 'Westslope Cutthroat Trout [Oncorhynchus clarkii  lewisi]' },
      { id: 1, description: 'White Meconella [Meconella oregana]' },
      { id: 1, description: 'White Sturgeon [Acipenser transmontanus]' },
      { id: 1, description: 'White-headed Woodpecker [Picoides albolarvatus]' },
      { id: 1, description: 'White-top Aster [Sericocarpus rigidus]' },
      { id: 1, description: 'Whitebark Pine [Pinus albicaulis]' },
      { id: 1, description: "Williamson's Sapsucker [Sphyrapicus thyroideus]" },
      { id: 1, description: 'Wolverine [Gulo gulo]' },
      { id: 1, description: 'Wood Bison [Bison bison  athabascae]' },
      { id: 1, description: 'Woodland Caribou [Rangifer tarandus  caribou]' },
      { id: 1, description: 'Yellow Montane Violet praemorsa subspecies [Viola praemorsa  ssp. praemorsa]' },
      { id: 1, description: 'Yellow Rail [Coturnicops noveboracensis]' },
      { id: 1, description: 'Yellow Scarab Hunter Wasp [Dielis pilipes]' },
      { id: 1, description: 'Yellow-banded Bumble Bee [Bombus terricola]' },
      { id: 1, description: 'Yellow-billed Loon [Gavia adamsii]' },
      { id: 1, description: 'Yellow-breasted Chat auricollis subspecies [Icteria virens  auricollis]' },
      { id: 1, description: 'Yelloweye Rockfish [Sebastes ruberrimus]' }
    ]
  };

  return result;
}
