version: '3.5'

services:
  ## Build the app docker image
  app:
    image: ${DOCKER_PROJECT_NAME}-app-${DOCKER_NAMESPACE}-img
    container_name: ${DOCKER_PROJECT_NAME}-app-${DOCKER_NAMESPACE}-container
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - LOCAL_API_HOST=app_api:${API_PORT}
    volumes:
      - ./:/opt/app-root/src
