apiVersion: v2
name: biohubbc
description: A Helm umbrella chart for SIMS BioHub BC - deploys app, database-setup, and api. For PR previews the database subchart (single-pod Postgres) is enabled; for static envs (dev/test/prod) database is disabled and Crunchy Postgres is deployed separately (see infrastructure/crunchy-db).
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: biohubbc-app
    repository: file://../app
    version: 0.1.0
    condition: app.enabled
  - name: biohubbc-db
    repository: file://../database
    version: 0.1.0
    condition: database.enabled
  - name: biohubbc-db-setup
    repository: file://../database-setup
    version: 0.1.0
    condition: database-setup.enabled
  - name: biohubbc-clamav
    repository: file://../clamav
    version: 0.1.0
    condition: clamav.enabled
  - name: biohubbc-api
    repository: file://../api
    version: 0.1.0
    condition: api.enabled
    dependsOn:
      - biohubbc-db-setup
