apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: biohubbc-app-dc
  labels:
    build: biohubbc-app
parameters:
  - name: NAME
    value: biohubbc-app
  - name: SUFFIX
    value: 'dev'
  - name: VERSION
    value: '1.0'
  - name: HOST
  - name: CHANGE_ID
    value: '0'
  - name: REACT_APP_BIOHUB_FEATURE_FLAG
    description: Flag to indicate if the application has biohub specific features enabled
    value: 'false'
  - name: REACT_APP_API_HOST
    description: API host for application backend
    value: ''
  - name: REACT_APP_SITEMINDER_LOGOUT_URL
    description: Siteminder URL to log out and clear the session for the logged in user
    value: ''
  - name: REACT_APP_MAX_UPLOAD_NUM_FILES
    description: Default maximum number of files that can be uploaded at a time vai the upload component UI.
    value: '10'
  - name: REACT_APP_MAX_UPLOAD_FILE_SIZE
    description: Default maximum size of a single file that can be uploaded by the upload component UI.
    value: '52428800'
  - name: NODE_ENV
    description: NODE_ENV specification variable
    value: 'development'
  - name: REACT_APP_NODE_ENV
    description: NODE_ENV specification variable for React app
    value: 'development'
  - name: OBJECT_STORE_SECRETS
    description: Secrets used to read and write to the S3 storage
    value: 'biohubbc-object-store'
  - name: APP_PORT_DEFAULT
    description: Application default port
    value: '7100'
  - name: APP_PORT_DEFAULT_NAME
    description: Default port resource name
    value: '7100-tcp'
  - name: REACT_APP_KEYCLOAK_HOST
    description: Key clock login url
    required: true
  - name: REACT_APP_KEYCLOAK_REALM
    description: Realm identifier or name
    required: true
  - name: REACT_APP_KEYCLOAK_CLIENT_ID
    description: Client Id for application
    required: true
  - name: REACT_APP_BACKBONE_PUBLIC_API_HOST
    description: Backbone API host for application frontend
  - name: REACT_APP_BIOHUB_TAXON_PATH
    description: Taxon path for biohub
  - name: REACT_APP_BIOHUB_TAXON_TSN_PATH
    description: Taxon TSN path for biohub
  - name: CPU_REQUEST
    value: '50m'
  - name: CPU_LIMIT
    value: '200m'
  - name: MEMORY_REQUEST
    value: '50Mi'
  - name: MEMORY_LIMIT
    value: '200Mi'
  - name: REPLICAS
    value: '1'
  - name: REPLICAS_MAX
    value: '1'
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        description: Nodejs Runtime Image
      labels:
        shared: 'true'
      generation: 0
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
      status:
        dockerImageRepository: null

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      generation: 0
      labels:
        role: app
      name: ${NAME}${SUFFIX}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        deploymentConfig: ${NAME}${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        type: Rolling
      template:
        metadata:
          annotations: null
          labels:
            deploymentConfig: ${NAME}${SUFFIX}
            role: app
        spec:
          containers:
            - name: app
              env:
                - name: CHANGE_VERSION
                  value: ${CHANGE_ID}
                - name: REACT_APP_API_HOST
                  value: ${REACT_APP_API_HOST}
                - name: REACT_APP_SITEMINDER_LOGOUT_URL
                  value: ${REACT_APP_SITEMINDER_LOGOUT_URL}
                - name: REACT_APP_MAX_UPLOAD_NUM_FILES
                  value: ${REACT_APP_MAX_UPLOAD_NUM_FILES}
                - name: REACT_APP_MAX_UPLOAD_FILE_SIZE
                  value: ${REACT_APP_MAX_UPLOAD_FILE_SIZE}
                - name: OBJECT_STORE_URL
                  valueFrom:
                    secretKeyRef:
                      key: object_store_url
                      name: ${OBJECT_STORE_SECRETS}
                - name: OBJECT_STORE_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: object_store_bucket_name
                      name: ${OBJECT_STORE_SECRETS}
                - name: NODE_ENV
                  value: ${NODE_ENV}
                - name: REACT_APP_BIOHUB_FEATURE_FLAG
                  value: ${REACT_APP_BIOHUB_FEATURE_FLAG}
                - name: REACT_APP_NODE_ENV
                  value: ${REACT_APP_NODE_ENV}
                - name: VERSION
                  value: ${VERSION}
                - name: REACT_APP_KEYCLOAK_HOST
                  value: ${REACT_APP_KEYCLOAK_HOST}
                - name: REACT_APP_KEYCLOAK_REALM
                  value: ${REACT_APP_KEYCLOAK_REALM}
                - name: REACT_APP_KEYCLOAK_CLIENT_ID
                  value: ${REACT_APP_KEYCLOAK_CLIENT_ID}
                - name: REACT_APP_BACKBONE_PUBLIC_API_HOST
                  value: ${REACT_APP_BACKBONE_PUBLIC_API_HOST}
                - name: REACT_APP_BIOHUB_TAXON_PATH
                  value: ${REACT_APP_BIOHUB_TAXON_PATH}
                - name: REACT_APP_BIOHUB_TAXON_TSN_PATH
                  value: ${REACT_APP_BIOHUB_TAXON_TSN_PATH}
              image: ' '
              imagePullPolicy: Always
              ports:
                - containerPort: ${{APP_PORT_DEFAULT}}
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              readinessProbe:
                httpGet:
                  path: /
                  port: ${{APP_PORT_DEFAULT}}
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 15
                successThreshold: 1
                failureThreshold: 20
              livenessProbe:
                httpGet:
                  path: /
                  port: ${{APP_PORT_DEFAULT}}
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 15
                successThreshold: 1
                failureThreshold: 20
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: ${NAME}${SUFFIX}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - app
            from:
              kind: ImageStreamTag
              name: ${NAME}:${VERSION}
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0

  - kind: Service
    apiVersion: v1
    metadata:
      annotations: null
      labels: {}
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: ${NAME}-${APP_PORT_DEFAULT_NAME}
          port: ${{APP_PORT_DEFAULT}}
          protocol: TCP
          targetPort: ${{APP_PORT_DEFAULT}}
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      annotations: {}
      labels: {}
      name: ${NAME}${SUFFIX}
    spec:
      host: ${HOST}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      port:
        targetPort: ${NAME}-${APP_PORT_DEFAULT_NAME}
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100
      wildcardPolicy: None
    status:
      ingress: null

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2
    metadata:
      annotations: {}
      labels: {}
      name: ${NAME}${SUFFIX}
    spec:
      minReplicas: ${{REPLICAS}}
      maxReplicas: ${{REPLICAS_MAX}}
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: ${NAME}${SUFFIX}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
