apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "environment.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
type: Opaque
data:
  database-name: {{ .Values.app.postgresDb | b64enc }}
  database-admin: {{ .Values.app.postgresAdmin | b64enc }}
  database-admin-password: {{ .Values.app.postgresAdminPassword | b64enc }}
  database-user: {{ .Values.app.postgresUser | b64enc }}
  database-user-password: {{ .Values.app.postgresUserPassword | b64enc }}
  database-user-api: {{ .Values.app.postgresUserApi | b64enc }}
  database-user-api-password: {{ .Values.app.postgresUserApiPassword | b64enc }}