apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  name: {{ include "app.fullname" . }}
  namespace: {{ include "environment.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.service.name }}
      nodePort: 0
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    name: {{ include "app.fullname" . | quote }}
  sessionAffinity: None
  type: {{ .Values.service.type }}