kind: Secret
apiVersion: v1
metadata:
  name: sims-database
data:
  database-admin: <fill in value>
  database-admin-password: <fill in value>
  database-name: <fill in value>
  database-user: <fill in value>
  database-user-api: <fill in value>
  database-user-api-password: <fill in value>
  database-user-password: <fill in value>
type: Opaque
