-- populate_first_nations.sql
insert into first_nations (name, record_effective_date) values ('Tla''amin Nation (Sliammon)', now());
insert into first_nations (name, record_effective_date) values ('Squamish Nation', now());
insert into first_nations (name, record_effective_date) values ('N''Quatqua Band (Anderson Lake)', now());
insert into first_nations (name, record_effective_date) values ('Lil''wat Nation (Mount Currie Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Aitchelitz Band', now());
insert into first_nations (name, record_effective_date) values ('Sts’ailes Nation (Chehalis Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Kwikwetlem First Nation', now());
insert into first_nations (name, record_effective_date) values ('Douglas First Nation (Xa’xtsa)', now());
insert into first_nations (name, record_effective_date) values ('Skatin Nations (Skookumchuck)', now());
insert into first_nations (name, record_effective_date) values ('Kwadacha Nation (Fort Ware)', now());
insert into first_nations (name, record_effective_date) values ('Lheidli-T''enneh First Nation', now());
insert into first_nations (name, record_effective_date) values ('Nadleh Whut''en Band (Fraser Lake) ', now());
insert into first_nations (name, record_effective_date) values ('Stellat''en First Nation', now());
insert into first_nations (name, record_effective_date) values ('Nak''azdli Band', now());
insert into first_nations (name, record_effective_date) values ('Saik''uz First Nation ', now());
insert into first_nations (name, record_effective_date) values ('Okanagan Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Tl''azt''en Nation', now());
insert into first_nations (name, record_effective_date) values ('McLeod Lake Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Kwiakah First Nations', now());
insert into first_nations (name, record_effective_date) values ('Mamalilikulla First Nation', now());
insert into first_nations (name, record_effective_date) values ('Mowachaht/Muchalaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('‘Namgis First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tlatlasikwala First Nation', now());
insert into first_nations (name, record_effective_date) values ('Quatsino First Nation', now());
insert into first_nations (name, record_effective_date) values ('Ehattesaht First Nation ', now());
insert into first_nations (name, record_effective_date) values ('Da''naxda''xw/Awaetlala First Nation (Tanakteuk Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Dzawada’enuxw First Nation (Tsawataineuk)', now());
insert into first_nations (name, record_effective_date) values ('Tlowitsis Nation', now());
insert into first_nations (name, record_effective_date) values ('Ka:''yu:''k''t''h''/Che:k:tles7et''h'' First Nation (Kyoquot)', now());
insert into first_nations (name, record_effective_date) values ('Nuchatlaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Scia''new First Nation (Beecher Bay)', now());
insert into first_nations (name, record_effective_date) values ('Stz''uminus First Nation (Chemainus)', now());
insert into first_nations (name, record_effective_date) values ('Cowichan Tribes', now());
insert into first_nations (name, record_effective_date) values ('Lake Cowichan First Nation', now());
insert into first_nations (name, record_effective_date) values ('Esquimalt Nation', now());
insert into first_nations (name, record_effective_date) values ('Burns Lake Indian Band (Ts''il Kaz Koh )', now());
insert into first_nations (name, record_effective_date) values ('Cheslatta Carrier Nation', now());
insert into first_nations (name, record_effective_date) values ('We Wai Kum First Nation (Campbell River Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('We Wai Kai First Nation (Cape Mudge Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('K’ómoks (Comox) First Nation', now());
insert into first_nations (name, record_effective_date) values ('Kwicksutaineuk/Ah-Kwa-Mish Tribes', now());
insert into first_nations (name, record_effective_date) values ('Kwakiutl Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Gwawaenuk Tribe', now());
insert into first_nations (name, record_effective_date) values ('Katzie First Nation', now());
insert into first_nations (name, record_effective_date) values ('Kwantlen First Nation (Fort Langley)', now());
insert into first_nations (name, record_effective_date) values ('Matsqui First Nation', now());
insert into first_nations (name, record_effective_date) values ('Qayqayt First Nation (New Westminister)', now());
insert into first_nations (name, record_effective_date) values ('Samahquam First Nation', now());
insert into first_nations (name, record_effective_date) values ('Scowlitz First Nation', now());
insert into first_nations (name, record_effective_date) values ('Semiahmoo First Nation', now());
insert into first_nations (name, record_effective_date) values ('Shxwhá:y Village (Skway) ', now());
insert into first_nations (name, record_effective_date) values ('Skowkale First Nation', now());
insert into first_nations (name, record_effective_date) values ('Soowahlie Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Skwah First Nation', now());
insert into first_nations (name, record_effective_date) values ('Squiala First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tzeachten First Nation', now());
insert into first_nations (name, record_effective_date) values ('Yakweakwioose First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tsawwassen First Nation', now());
insert into first_nations (name, record_effective_date) values ('Sumas First Nation', now());
insert into first_nations (name, record_effective_date) values ('Leq''a:mel First Nation (Lakahahmen)', now());
insert into first_nations (name, record_effective_date) values ('Kwaw-kwaw-a-pilt First Nation', now());
insert into first_nations (name, record_effective_date) values ('Seabird Island Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Skawahlook First Nation', now());
insert into first_nations (name, record_effective_date) values ('Chawathil Band (Hope)', now());
insert into first_nations (name, record_effective_date) values ('Cheam First Nation', now());
insert into first_nations (name, record_effective_date) values ('Popkum Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Peters Band', now());
insert into first_nations (name, record_effective_date) values ('Shxw''ow''hamel First Nation', now());
insert into first_nations (name, record_effective_date) values ('Union Bar Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Yale First Nation', now());
insert into first_nations (name, record_effective_date) values ('Bridge River Indian Band (Nxwisten)', now());
insert into first_nations (name, record_effective_date) values ('Cayoose Creek Band (Sekw''el''was)', now());
insert into first_nations (name, record_effective_date) values ('Xaxli''p First Nation (Fountain)', now());
insert into first_nations (name, record_effective_date) values ('T''it''q''et (Lillooet Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Ts''kw''aylaxw First Nation', now());
insert into first_nations (name, record_effective_date) values ('Seton Lake Band (Tsal''alh)', now());
insert into first_nations (name, record_effective_date) values ('Osoyoos Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Penticton Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Lower Similkameen Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Upper Similkameen Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Splatsin (Spallumcheen) Band', now());
insert into first_nations (name, record_effective_date) values ('Westbank First Nation', now());
insert into first_nations (name, record_effective_date) values ('St. Mary''s Indian Band (?Aq''am)', now());
insert into first_nations (name, record_effective_date) values ('Tobacco Plains Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Columbia Lake Indian Band (?Akisq''nuk First Nation)', now());
insert into first_nations (name, record_effective_date) values ('Shuswap Band', now());
insert into first_nations (name, record_effective_date) values ('Lower Kootenay Indian Band (Yaqan nu?kiy)', now());
insert into first_nations (name, record_effective_date) values ('Lake Babine Nation', now());
insert into first_nations (name, record_effective_date) values ('Takla Lake First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tsay Keh Dene', now());
insert into first_nations (name, record_effective_date) values ('Taku River Tlingit First Nation (Atlin First Nation)', now());
insert into first_nations (name, record_effective_date) values ('Liard First Nation', now());
insert into first_nations (name, record_effective_date) values ('Dease River Band Council', now());
insert into first_nations (name, record_effective_date) values ('Moricetown Band Administration', now());
insert into first_nations (name, record_effective_date) values ('Gitanmaax Band Council', now());
insert into first_nations (name, record_effective_date) values ('Kispiox Band Council', now());
insert into first_nations (name, record_effective_date) values ('Glen Vowell Indian Band (Sik-e-Dakh)', now());
insert into first_nations (name, record_effective_date) values ('Hagwilget Village Council ', now());
insert into first_nations (name, record_effective_date) values ('Gitsegukla Indian Band (Kitsegugkla)', now());
insert into first_nations (name, record_effective_date) values ('Gitwangak Band Council (Kitwanga)', now());
insert into first_nations (name, record_effective_date) values ('Gitanyow Hereditary Chiefs', now());
insert into first_nations (name, record_effective_date) values ('Heiltsuk Nation (Bella Bella Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Nuxalk Nation (Bella Coola Band)', now());
insert into first_nations (name, record_effective_date) values ('Kitasoo/Xai''xais Band Council (Klemtu)', now());
insert into first_nations (name, record_effective_date) values ('Wuikinuxv First Nation (Oweekeno)', now());
insert into first_nations (name, record_effective_date) values ('Saulteau First Nations', now());
insert into first_nations (name, record_effective_date) values ('Fort Nelson First Nation', now());
insert into first_nations (name, record_effective_date) values ('Prophet River Band (Denetsaa Tse K''Nai)', now());
insert into first_nations (name, record_effective_date) values ('West Moberly First Nations ', now());
insert into first_nations (name, record_effective_date) values ('Halfway River First Nations', now());
insert into first_nations (name, record_effective_date) values ('Blueberry River First Nations', now());
insert into first_nations (name, record_effective_date) values ('Doig River First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tsleil-Waututh First Nation (Burrard Band)', now());
insert into first_nations (name, record_effective_date) values ('Musqueam Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Sechelt Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Homalco (Xwemalhkwu) Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Klahoose First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tsawout First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tseycum First Nation', now());
insert into first_nations (name, record_effective_date) values ('Songhees First Nation', now());
insert into first_nations (name, record_effective_date) values ('T''Sou-ke Nation (Sooke)', now());
insert into first_nations (name, record_effective_date) values ('Pacheedaht First Nation ', now());
insert into first_nations (name, record_effective_date) values ('Ahousaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tla-o-qui-aht First Nation (Clayoquot)', now());
insert into first_nations (name, record_effective_date) values ('Hesquiaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Ditidaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Metlakatla First Nation', now());
insert into first_nations (name, record_effective_date) values ('Laxkw''alaams Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Hartley Bay Village Council (Gitga''at)', now());
insert into first_nations (name, record_effective_date) values ('Haisla Nation (Kitimaat Village Council)', now());
insert into first_nations (name, record_effective_date) values ('Gitlaxt''aamix Village Government (New Aiyansh)', now());
insert into first_nations (name, record_effective_date) values ('Laxgalts''ap Village Government', now());
insert into first_nations (name, record_effective_date) values ('Gitwinksihlkw Village Government', now());
insert into first_nations (name, record_effective_date) values ('Kitselas Nation', now());
insert into first_nations (name, record_effective_date) values ('Kitsumkalum First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tahltan Band Council', now());
insert into first_nations (name, record_effective_date) values ('Iskut First Nation', now());
insert into first_nations (name, record_effective_date) values ('Adams Lake Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Ashcroft Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Bonaparte Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Skeetchestn Indian Band (Deadman''s Creek)', now());
insert into first_nations (name, record_effective_date) values ('Tk''emlúps te Secwepemc (Kamloops Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Little Shuswap Lake Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Neskonlith Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Simpcw First Nation (North Thompson River)', now());
insert into first_nations (name, record_effective_date) values ('Oregon Jack Creek Band', now());
insert into first_nations (name, record_effective_date) values ('Coldwater Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Cook''s Ferry Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Lower Nicola Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Nicomen Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Upper Nicola Band', now());
insert into first_nations (name, record_effective_date) values ('Shackan Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Nooaitch Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Boothroyd Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Boston Bar First Nation', now());
insert into first_nations (name, record_effective_date) values ('Whispering Pines / Clinton Indian Band', now());
insert into first_nations (name, record_effective_date) values ('High Bar First Nation', now());
insert into first_nations (name, record_effective_date) values ('Kanaka Bar Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Lytton First Nation', now());
insert into first_nations (name, record_effective_date) values ('Siska Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Skuppah Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Spuzzum First Nation', now());
insert into first_nations (name, record_effective_date) values ('Huu-ay-aht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Hupacasath First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tseshaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Toquaht First Nation', now());
insert into first_nations (name, record_effective_date) values ('Uchucklesaht Tribe ', now());
insert into first_nations (name, record_effective_date) values ('Ucluelet First Nation (uułuʔiłʔatḥ)', now());
insert into first_nations (name, record_effective_date) values ('Old Masset Village Council', now());
insert into first_nations (name, record_effective_date) values ('Skidegate Band Council', now());
insert into first_nations (name, record_effective_date) values ('Gingolx Village Government (Kincolith)', now());
insert into first_nations (name, record_effective_date) values ('Gitxaala Nation (Kitkatla)', now());
insert into first_nations (name, record_effective_date) values ('Halalt First Nation', now());
insert into first_nations (name, record_effective_date) values ('Lyackson First Nations', now());
insert into first_nations (name, record_effective_date) values ('Malahat Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Snuneymuxw First Nation', now());
insert into first_nations (name, record_effective_date) values ('Snaw-Naw-As First Nation (Nanoose)', now());
insert into first_nations (name, record_effective_date) values ('Penelakut Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Qualicum First Nation ', now());
insert into first_nations (name, record_effective_date) values ('Pauquachin First Nation', now());
insert into first_nations (name, record_effective_date) values ('Tsartlip First Nation', now());
insert into first_nations (name, record_effective_date) values ('Alexandria Indian Band (?Esdilagh First Nation)', now());
insert into first_nations (name, record_effective_date) values ('Alexis Creek First Nation (Tsi Del Del)', now());
insert into first_nations (name, record_effective_date) values ('Esk''etemc First Nation', now());
insert into first_nations (name, record_effective_date) values ('Anaham Indian Band (Tl''etinqox-t''in Government Office)', now());
insert into first_nations (name, record_effective_date) values ('Canim Lake Indian Band (Tsq''escen’)', now());
insert into first_nations (name, record_effective_date) values ('Xeni Gwet-in First Nations Government (Nemiah)', now());
insert into first_nations (name, record_effective_date) values ('Lhtako Dene Nation (Red Buff Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Xat''sull First Nation (Soda Creek)', now());
insert into first_nations (name, record_effective_date) values ('Yunesit''in First Nation (Stone)', now());
insert into first_nations (name, record_effective_date) values ('Toosey Indian Band (Tl''esqox)', now());
insert into first_nations (name, record_effective_date) values ('Williams Lake Indian Band', now());
insert into first_nations (name, record_effective_date) values ('Nazko First Nation', now());
insert into first_nations (name, record_effective_date) values ('Lhoosk''uz Dene Nation (Kluskus Indian Band)', now());
insert into first_nations (name, record_effective_date) values ('Ulkatcho First Nation', now());
insert into first_nations (name, record_effective_date) values ('Canoe Creek Indian Band (Stswecem''c Xgat''tem First Nation)', now());
insert into first_nations (name, record_effective_date) values ('Gwa''sala-''Nakwaxda''xw Nation', now());
insert into first_nations (name, record_effective_date) values ('Wet''suwet''en First Nation (Broman Lake)', now());
insert into first_nations (name, record_effective_date) values ('Nee-Tahi-Buhn Band', now());
insert into first_nations (name, record_effective_date) values ('Yekooche First Nation', now());
insert into first_nations (name, record_effective_date) values ('Skin Tyee Band', now());
insert into first_nations (name, record_effective_date) values ('Carcross/Tagish First Nation', now());
insert into first_nations (name, record_effective_date) values ('Champagne and Aishihik First Nations', now());
insert into first_nations (name, record_effective_date) values ('Ross River Dene Council', now());
insert into first_nations (name, record_effective_date) values ('Teslin Tlingit Council', now());
insert into first_nations (name, record_effective_date) values ('Acho Dene Koe First Nation', now());