kind: Template
apiVersion: v1
metadata:
  name: migration
  creationTimestamp: null
parameters:
  - name: IMAGE
    description: 'Image for pod'
    required: true
  - name: NAME
    value: biohubbc-db-setup
  - name: SUFFIX
    value: '-dev'
  - name: VERSION
    description: Version of the application
    value: '1.0.0'
  - name: CHANGE_ID
    description: Change id of the project. This will help to pull image stream
    required: true
    value: '0'
  - name: DB_SERVICE_NAME
    description: 'Database service name associated  with deployment'
    required: true
  - name: NODE_ENV
    description: Application Environment type variable
    required: true
    value: 'dev'
  - name: CPU_REQ
    value: '500m'
  - name: CPU_LIMIT
    value: '750m'
  - name: MEMORY_REQ
    value: '1Gi'
  - name: MEMORY_LIMIT
    value: '2Gi'
  - name: REPLICAS
    value: '1'
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: '${NAME}'
      creationTimestamp:
      labels: {}
    spec:
      containers:
        - name: test
          image: '${IMAGE}'
          resources:
            limits:
              cpu: '1'
              memory: 1.5Gi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: DB_HOST
              value: ${DB_SERVICE_NAME}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: database-root-user
                  name: ${DB_SERVICE_NAME}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: ${DB_SERVICE_NAME}
            - name: DB_USER_API
              value: 'biohub_api'
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: ${DB_SERVICE_NAME}
            - name: DB_PORT
              value: '5432'
            - name: CHANGE_VERSION
              value: ${CHANGE_ID}
            - name: NODE_ENV
              value: ${NODE_ENV}
            - name: VERSION
              value: ${VERSION}
            - name: DB_SCHEMA
              value: 'biohub'
            - name: DB_SCHEMA_DAPI_V1
              value: 'biohub_dapi_v1'
          imagePullPolicy: Always
      restartPolicy: Never
      activeDeadlineSeconds: 900
      dnsPolicy: ClusterFirst
    status: {}
