-- populate_funding_source.sql
insert into funding_source (name, record_effective_date, project_id_optional) values ('Together for Wildlife', now(), 'N');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Land Based Investment Strategy', now(), 'N');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Caribou Recovery Program', now(), 'N');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Habitat Conservation Trust Fund', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fish and Wildlife Compensation Program - Peace', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fish and Wildlife Compensation Program - Columbia', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fish and Wildlife Compensation Program - Coastal', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Ministry of Forests, Lands, Natural Resource Operations, and Rural Development', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Ministry of Environment and Climate Change Strategy', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fresh Water Fisheries Society', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('BC Hydro', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('BC Parks Living Labs', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('BC Parks Licence Plate Program', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('BC Timber Sales', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Carbon Offset Investment', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Canada Nature Fund', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Canadian Wildlife Services', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Caribou Recovery Fund', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Department of Fisheries and Ocean', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Ducks Unlimited', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Ecosystem Restoration Program', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fraser Basin Council', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Fraser River Sturgeon Conservation Society', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Forest Enhancement Society', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Forests for Tomorrow', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Freshwater Fisheries Society of BC', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Habitat Conservation Trust Foundation', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Nature Conservancy of Canada', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Natural Resources Canada', now(), 'Y');
insert into funding_source (name, record_effective_date, project_id_optional) values ('Nature Trust', now(), 'Y');
