export const coordinator_agency = [
  { id: 1, name: 'A Rocha Canada' },
  { id: 2, name: 'Aarde Environmental Ltd.' },
  { id: 3, name: 'Acres Consulting' },
  { id: 4, name: 'Advisian' },
  { id: 5, name: 'AECOM Canada Ltd.' },
  { id: 6, name: 'Alaska Department of Fish and Game' },
  { id: 7, name: 'Alces Environmental Ltd.' },
  { id: 8, name: 'Allnorth Consultants Limited' },
  { id: 9, name: 'Allouette River Management Society' },
  { id: 10, name: 'AMEC Earth and Environmental' },
  { id: 11, name: 'Applied Aquatic Research Ltd.' },
  { id: 12, name: 'Applied Ecological Solutions Corp.' },
  { id: 13, name: 'Aquaparian Environmental Consulting Ltd.' },
  { id: 14, name: 'AquaSilva Resource Management Ltd.' },
  { id: 15, name: 'Aqua-Tex Scientific Consulting Ltd. ' },
  { id: 16, name: 'Associated Environmental Consultants Inc.' },
  { id: 17, name: 'Association of Wetland Stewards for Clayoquot and Barkley Sounds' },
  { id: 18, name: 'Assuage Environmental Ltd.' },
  { id: 19, name: 'Aurico Metals Inc.' },
  { id: 20, name: 'Avison Management Services Ltd.' },
  { id: 21, name: 'Azimuth Consulting Group Partnership' },
  { id: 22, name: 'Balanced Ecological Management Company' },
  { id: 23, name: 'Bamfield Marine Sciences Centre' },
  { id: 24, name: 'BBA Engineering Ltd.' },
  { id: 25, name: 'BC Conservation Foundation (BCCF)' },
  { id: 26, name: 'BC Hydro' },
  { id: 27, name: 'BCIT Fish Wildlife and Recreation Program' },
  { id: 28, name: 'Burt and Associates' },
  { id: 29, name: 'Canadian Forest Products' },
  { id: 30, name: 'Capital Regional District (CRD)' },
  { id: 31, name: 'Cariboo Environmental Quality Consulting Ltd.' },
  { id: 32, name: 'Cariboo Envirotech Ltd.' },
  { id: 33, name: 'Carleton University' },
  { id: 34, name: 'Cascade Environmental Resource Group Ltd.' },
  { id: 35, name: 'Castus Environmental Services Ltd.' },
  { id: 36, name: 'Central Westcoast Forest Society' },
  { id: 37, name: 'Chu Cho Environmental' },
  { id: 38, name: 'City of Abbotsford' },
  { id: 39, name: 'City of Chilliwack' },
  { id: 40, name: 'City of Coquitlam' },
  { id: 41, name: 'City of Kelowna Environment Division' },
  { id: 42, name: 'Clark University' },
  { id: 43, name: 'Clearwater Environmental Consulting' },
  { id: 44, name: 'Coast River Environmental Services Ltd.' },
  { id: 45, name: 'Coldstream Ecology Ltd.' },
  { id: 46, name: 'College of New Caledonia' },
  { id: 47, name: 'Columbia Environmental Consulting Ltd.' },
  { id: 48, name: 'Columbia Power Corporation' },
  { id: 49, name: 'Colville Confederated Tribes Fish and Wildlife' },
  { id: 50, name: 'Comox Valley Project Watershed Society' },
  { id: 51, name: 'Cooper Beauchesne and Associates Ltd.' },
  { id: 52, name: 'Copcan Contracting Ltd.' },
  { id: 53, name: 'Cornice Environmental Consulting Ltd.' },
  { id: 54, name: 'Corvidae Environmental Consulting Inc.' },
  { id: 55, name: 'Crane Creek Enterprises' },
  { id: 56, name: 'CSR Environmental Ltd.' },
  { id: 57, name: 'Current Environmental Ltd.' },
  { id: 58, name: 'D. Burt and Associates' },
  { id: 59, name: 'D.R. Clough Consulting' },
  { id: 60, name: 'David Bustard and Associates Ltd.' },
  { id: 61, name: 'Davis Environmental Ltd.' },
  { id: 62, name: 'Dayesi Services' },
  { id: 63, name: 'Department of Fisheries and Oceans (DFO)' },
  { id: 64, name: 'DGR Consulting' },
  { id: 65, name: 'Dillon Consulting Limited' },
  { id: 66, name: 'District of Kent' },
  { id: 67, name: 'District of North Vancouver' },
  { id: 68, name: 'District of Saanich' },
  { id: 69, name: 'Diversified Environmental Services Ltd.' },
  { id: 70, name: 'DWB Consulting Services Ltd.' },
  { id: 71, name: 'East Carolina University - Department of Biology' },
  { id: 72, name: 'EBB Environmental Consulting Inc.' },
  { id: 73, name: 'Ecofish Research Ltd.' },
  { id: 74, name: 'Ecofor Consulting' },
  { id: 75, name: 'Ecologic Consulting Ltd.' },
  { id: 76, name: 'EcoMetrix Incorporated' },
  { id: 77, name: 'Ecora Engineering and Resource Group Ltd.' },
  { id: 78, name: 'Ecoscape Environmental Consultants Ltd.' },
  { id: 79, name: 'Eco-Web Ecological Consulting Ltd.' },
  { id: 80, name: 'EDI Environmental Dynamics Inc.' },
  { id: 81, name: 'Elevate Environmental Inc.' },
  { id: 82, name: 'Elk River Alliance' },
  { id: 83, name: 'ENKON Environmental Ltd.' },
  { id: 84, name: 'Envirologic Consulting Inc.' },
  { id: 85, name: 'Environment and Climate Change Canada' },
  { id: 86, name: 'Envirowest Consultants Inc.' },
  { id: 87, name: 'ERM Consultants Canada Ltd.' },
  { id: 88, name: 'Esther Guimond Consulting' },
  { id: 89, name: 'Estsek Environmental Services LLP' },
  { id: 90, name: 'EXP Services Inc.' },
  { id: 91, name: 'FINS Consulting Ltd.' },
  { id: 92, name: 'Fish-Kissing Weasels Environmental' },
  { id: 93, name: 'ForFish Consulting' },
  { id: 94, name: 'Forsite Consultants Ltd.' },
  { id: 95, name: 'FortisBC' },
  { id: 96, name: 'Fraser Valley Watersheds Coalition' },
  { id: 97, name: 'Freshwater Fisheries Society of BC' },
  { id: 98, name: 'FSCI Biological Concultants' },
  { id: 99, name: 'G3 Consulting Ltd.' },
  { id: 100, name: 'GeoMarine Environmental Consultants Ltd.' },
  { id: 101, name: 'GG Oliver and Associates Environmental Science' },
  { id: 102, name: 'Gitanyow Fisheries Authority' },
  { id: 103, name: 'Gitksan Watershed Authorities' },
  { id: 104, name: 'Golder Associates Ltd.' },
  { id: 105, name: 'Grassroots Environmental Services' },
  { id: 106, name: 'Hatfield Consulting Ltd.' },
  { id: 107, name: 'HCR Environmental Consulting' },
  { id: 108, name: 'Hemmera' },
  { id: 109, name: 'High Country Consulting' },
  { id: 110, name: 'Hill Environmental Ltd.' },
  { id: 111, name: 'Hocquard Consulting' },
  { id: 112, name: 'I.C. Ramsay and Associates' },
  { id: 113, name: 'Ingersol Mountain Enterprise Ltd.' },
  { id: 114, name: 'Inland Timber Management Ltd.' },
  { id: 115, name: 'InStream Fisheries Research Inc.' },
  { id: 116, name: 'Interior Reforestation Co. Ltd.' },
  { id: 117, name: 'IRC Integrated Resource Consultants Inc.' },
  { id: 118, name: 'ISL Engineering and Land Services Ltd.' },
  { id: 119, name: 'Iverson & MacKenzie Biological Consulting Ltd.' },
  { id: 120, name: 'Jacobs Canada Inc.' },
  { id: 121, name: 'JBL Environmental Services Ltd.' },
  { id: 122, name: 'Karen L Grainger' },
  { id: 123, name: 'Kawa Enginnering Ltd.' },
  { id: 124, name: 'Kerr Wood Leidal Associates Ltd.' },
  { id: 125, name: 'Keystone Environmental Ltd.' },
  { id: 126, name: 'Klohn Crippen Berger Ltd.' },
  { id: 127, name: 'Knight Piesold Ltd.' },
  { id: 128, name: 'Ktunaxa Nation Council' },
  { id: 129, name: 'Lake Trail Environmental Consulting' },
  { id: 130, name: 'Letts Environmental Consultants Ltd.' },
  { id: 131, name: 'LGL Limited' },
  { id: 132, name: 'Lheidli T Enneh First Nations' },
  { id: 133, name: 'Limnotek Research and Development Inc.' },
  { id: 134, name: 'Living Resources Environmental' },
  { id: 135, name: 'Lorax Environmental Services Ltd.' },
  { id: 136, name: 'Lotic Environmental Ltd.' },
  { id: 137, name: 'M.C. Wright and Associates Ltd.' },
  { id: 138, name: 'Madrone Environmental Services Ltd.' },
  { id: 139, name: 'Mainstream Aquatics Ltd.' },
  { id: 140, name: 'Mainstream Biological Consulting Inc.' },
  { id: 141, name: 'Marine Harvest Canada' },
  { id: 142, name: 'Marlim Ecological Consulting Ltd.' },
  { id: 143, name: 'Masse Environmental Consultants Ltd.' },
  { id: 144, name: 'Matrix Solutions Inc.' },
  { id: 145, name: 'Max Planck Institute, Ploen, Germany' },
  { id: 146, name: 'McCleary Aquatic Systems Consulting' },
  { id: 147, name: 'McElhanney Ltd.' },
  { id: 148, name: 'McGill University, Redpath Museum' },
  { id: 149, name: 'McTavish Resource & Management Consultants Ltd.' },
  { id: 150, name: 'Metro Vancouver (GVRD)' },
  { id: 151, name: 'Metro Vancouver Regional Parks' },
  { id: 152, name: 'Michigan State University' },
  { id: 153, name: 'Mid Vancouver Island Habitat Enhancement Society' },
  { id: 154, name: 'Ministry of Environment & Climate Change Strategy' },
  { id: 155, name: 'Ministry of Forests, Lands, Natural Resource Operations & Rural Development' },
  { id: 156, name: 'Ministry of Transportation & Infrastructure' },
  { id: 157, name: 'Minnow Environmental Inc.' },
  { id: 158, name: 'Montana Fish, Wildlife & Parks' },
  { id: 159, name: 'Mount Polley Mining Corporation' },
  { id: 160, name: 'Mountain Water Research' },
  { id: 161, name: 'Naito Environmental' },
  { id: 162, name: 'Natural Resources Training Group (NRTG)' },
  { id: 163, name: 'Nature Conservancy of Canada' },
  { id: 164, name: 'Nautilus Environmental Company Ltd.' },
  { id: 165, name: 'Nicola Valley Institute of Technology (NVIT)' },
  { id: 166, name: 'North Coast Skeena First Nations Stewardship Society' },
  { id: 167, name: 'North River Consulting Ltd.' },
  { id: 168, name: 'Northern (Arctic) Federal University (NArFU)' },
  { id: 169, name: 'Northern Van Island Salmonid Enhancement Assoc.' },
  { id: 170, name: 'Northland Environmental Ltd.' },
  { id: 171, name: 'Northwest Community College' },
  { id: 172, name: 'Nova Pacific Environmental Ltd.' },
  { id: 173, name: 'Nupqu Development Corporation' },
  { id: 174, name: 'Ogopogo Environmental & Engineering Consultants Ltd.' },
  { id: 175, name: 'Okanagan Nation Alliance' },
  { id: 176, name: 'Pacificus Biological Services Ltd.' },
  { id: 177, name: 'Palmer Environmental Consulting Group Inc.' },
  { id: 178, name: 'Pearson Ecological' },
  { id: 179, name: 'Peninsula Streams Society' },
  { id: 180, name: 'Phoenix Environmental Services Ltd.' },
  { id: 181, name: 'Pinchin Ltd.' },
  { id: 182, name: 'Poisson Consulting Ltd.' },
  { id: 183, name: 'Polaris Environmental Consultants Ltd.' },
  { id: 184, name: 'Pottinger Gaherty Environmental Consultants Ltd.' },
  { id: 185, name: 'Profor Resource Development Inc.' },
  { id: 186, name: 'Qqs Projects Society' },
  { id: 187, name: 'Quatse River Hatchery' },
  { id: 188, name: 'Quesnel River Environmental Restoration Services' },
  { id: 189, name: 'Red Chris Development Company Ltd.' },
  { id: 190, name: 'Redcedar Environmental Consulting Inc.' },
  { id: 191, name: 'Resort Municipality of Whistler' },
  { id: 192, name: 'Roy Northern Environmental Ltd.' },
  { id: 193, name: 'Sage Environmental Consulting Ltd.' },
  { id: 194, name: 'Salmon Coast Field Station Society' },
  { id: 195, name: 'Sartori Environmental Services Inc.' },
  { id: 196, name: 'School District 54' },
  { id: 197, name: 'Secwepemc Fisheries Commission' },
  { id: 198, name: 'Selkirk College' },
  { id: 199, name: 'SER Environmental Management' },
  { id: 200, name: 'Seven Generations Environmental Services Ltd.' },
  { id: 201, name: 'Shawn Hamilton and Associates' },
  { id: 202, name: 'Shawnigan Lake School' },
  { id: 203, name: 'Shuksan Fisheries Consulting' },
  { id: 204, name: 'Silvatech Consulting Ltd.' },
  { id: 205, name: 'Simon Fraser University (SFU) - Biological Sciences' },
  { id: 206, name: 'SKR Consultants Ltd.' },
  { id: 207, name: 'SLR Consulting (Canada) Ltd.' },
  { id: 208, name: 'SNC Lavalin Inc.' },
  { id: 209, name: 'Splatsin DC - Yucwmenlucwu LLC' },
  { id: 210, name: 'St at imc Eco-Resources Ltd.' },
  { id: 211, name: 'Stanley Park Ecology Society' },
  { id: 212, name: 'Stantec Consulting Ltd.' },
  { id: 213, name: 'Strategic Forest Management Inc.' },
  { id: 214, name: 'Strategic Natural Resource Consultants Inc.' },
  { id: 215, name: 'Sunshine Coast Salmonid Enhancement Society' },
  { id: 216, name: 'Taan Forest Ltd.' },
  { id: 217, name: 'Teck Coal Limited' },
  { id: 218, name: 'Teck Highland Valley Copper Partnership' },
  { id: 219, name: 'TERA Planning Ltd.' },
  { id: 220, name: 'Tetra Tech Canada Inc.' },
  { id: 221, name: 'Tetra Tech EBA' },
  { id: 222, name: 'Thompson Rivers University' },
  { id: 223, name: 'Tisdale Environmental Consulting Inc.' },
  { id: 224, name: 'Titus Biological Services Inc.' },
  { id: 225, name: 'Toba Montrose Hydro Inc.' },
  { id: 226, name: 'Trinity Western University' },
  { id: 227, name: 'Triton Environmental Consultants Ltd.' },
  { id: 228, name: 'Triton Environmental Consultants Ltd. (Calgary)' },
  { id: 229, name: 'Triton Environmental Consultants Ltd. (Kamloops)' },
  { id: 230, name: 'Triton Environmental Consultants Ltd. (Nanaimo)' },
  { id: 231, name: 'Triton Environmental Consultants Ltd. (Prince George)' },
  { id: 232, name: 'Triton Environmental Consultants Ltd. (Richmond)' },
  { id: 233, name: 'Triton Environmental Consultants Ltd. (Terrace)' },
  { id: 234, name: 'University of Alberta' },
  { id: 235, name: 'University of Bern, Institute of Ecology and Evolution' },
  { id: 236, name: 'University of British Columbia' },
  { id: 237, name: 'University of British Columbia (UBC) - Okanagan' },
  { id: 238, name: 'University of Calgary' },
  { id: 239, name: 'University of Lethbridge' },
  { id: 240, name: 'University of Montana' },
  { id: 241, name: 'University of Montreal' },
  { id: 242, name: 'University of New Brunswick' },
  { id: 243, name: 'University of Northern British Columbia' },
  { id: 244, name: 'University of Texas at Austin' },
  { id: 245, name: 'University of Victoria' },
  { id: 246, name: 'Urban Systems Ltd.' },
  { id: 247, name: 'uTree Environmental Consultants Ltd.' },
  { id: 248, name: 'Valley Environmental' },
  { id: 249, name: 'Vancouver Island University' },
  { id: 250, name: 'Vast Resource Solutions Inc.' },
  { id: 251, name: 'Vision Marine Consulting Ltd.' },
  { id: 252, name: 'Wapta Environmental Consulting Ltd.' },
  { id: 253, name: 'Watershed Ecological Services Ltd.' },
  { id: 254, name: 'Western Forest Products Inc.' },
  { id: 255, name: 'Western Water Associates Ltd.' },
  { id: 256, name: 'Westland Resources Ltd.' },
  { id: 257, name: 'Westslope Fisheries' },
  { id: 258, name: 'White Pine Environmental Resources Inc.' },
  { id: 259, name: 'Whitehead Environmental Consultants Ltd.' },
  { id: 260, name: 'Wildlife Infometrics Inc.' },
  { id: 261, name: 'Wood PLC' },
  { id: 262, name: 'WorleyParsons Canada Service Ltd.' },
  { id: 263, name: 'WSP Canada Inc.' },
  { id: 264, name: 'Yukon Energy Corporation' },
  { id: 265, name: 'Other' }
];

export const region = [
  { id: 1, name: 'West Coast' },
  { id: 2, name: 'South Coast' },
  { id: 3, name: 'Kootenay-Boundary' },
  { id: 4, name: 'Thompson-Okanagan' },
  { id: 5, name: 'Cariboo' },
  { id: 6, name: 'Skeena' },
  { id: 7, name: 'Omineca' },
  { id: 8, name: 'Northeast' },
  { id: 9, name: 'Province' }
];

export const regional_offices = [
  { id: 1, name: 'Office 1' },
  { id: 2, name: 'Office 2' },
  { id: 3, name: 'Office 3' }
];
