// Message types that match the submission_message_type table
export enum SUBMISSION_MESSAGE_TYPE {
  'DUPLICATE_HEADER' = 'Duplicate Header',
  'UNKNOWN_HEADER' = 'Unknown Header',
  'MISSING_REQUIRED_HEADER' = 'Missing Required Header',
  'MISSING_RECOMMENDED_HEADER' = 'Missing Recommended Header',
  'DANGLING_PARENT_CHILD_KEY' = 'Missing Child Key from Parent',
  'MISCELLANEOUS' = 'Miscellaneous',
  'MISSING_REQUIRED_FIELD' = 'Missing Required Field',
  'UNEXPECTED_FORMAT' = 'Unexpected Format',
  'OUT_OF_RANGE' = 'Out of Range',
  'INVALID_VALUE' = 'Invalid Value',
  'MISSING_VALIDATION_SCHEMA' = 'Missing Validation Schema',
  'FAILED_GET_OCCURRENCE' = 'Failed to Get Occurrence Submission',
  'FAILED_GET_FILE_FROM_S3' = 'Failed to get file from S3',
  'FAILED_UPLOAD_FILE_TO_S3' = 'Failed to upload file to S3',
  'FAILED_PARSE_SUBMISSION' = 'Failed to parse submission',
  'FAILED_PREP_XLSX' = 'Failed to prep XLSX',
  'FAILED_PERSIST_PARSE_ERRORS' = 'Failed to persist parse errors',
  'FAILED_GET_VALIDATION_RULES' = 'Failed to get validation rules',
  'FAILED_GET_TRANSFORMATION_RULES' = 'Failed to get transformation rules',
  'FAILED_PERSIST_TRANSFORMATION_RESULTS' = 'Failed to persist transformation results',
  'FAILED_PERSIST_VALIDATION_RESULTS' = 'Failed to persist validation results',
  'FAILED_UPDATE_OCCURRENCE_SUBMISSION' = 'Failed to update occurrence submission',
  'FAILED_TO_GET_TRANSFORM_SCHEMA' = 'Unable to get transform schema for submission',
  'FAILED_TO_GET_TEMPLATE_NAME_VERSION' = 'Missing name or version number.',
  'INVALID_MEDIA' = 'Media is invalid',
  'INVALID_XLSX_CSV' = 'Media is not a valid XLSX CSV file.',
  'UNSUPPORTED_FILE_TYPE' = 'File submitted is not a supported type',
  'NON_UNIQUE_KEY' = 'Duplicate Key(s) found in file.',
  'MISMATCHED_TEMPLATE_SURVEY_SPECIES' = 'Mismatched template with survey focal species'
}
