version: '3.5'

services:
  # https://blog.knoldus.com/deployment-with-docker-in-ionic/ #########################################################
  ## Build the app docker image
  app:
    image: ${DOCKER_PROJECT_NAME}-app-ionic-${DOCKER_NAMESPACE}-setup-img
    container_name: ${DOCKER_PROJECT_NAME}-app-ionic-${DOCKER_NAMESPACE}-setup-container
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    ports:
      - ${APP_IONIC_PORT}:${APP_IONIC_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_IONIC_PORT=${APP_IONIC_PORT}
      - LOCAL_API_HOST=app_api:${REACT_APP_API_PORT}
    volumes:
      - ./:/opt/app-root/src
