import { Knex } from 'knex';

const DB_SCHEMA = process.env.DB_SCHEMA;

export async function up(knex: Knex): Promise<void> {
  await knex.raw(`

  set schema '${DB_SCHEMA}';
  set search_path = ${DB_SCHEMA},public;

  CREATE TABLE user_group(
    user_group_id              integer           GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    name character varying(300) NOT NULL,
    group_type character varying(25),
    affiliation character varying(25),
    email_address character varying(50),
    phone_number character varying(25),
    web_page character varying(255),
    province_state character varying(25),
    country character varying(25),
    record_end_date          date,
    record_effective_date    date              NOT NULL,
    create_date              timestamptz(6)    DEFAULT now() NOT NULL,
    create_user              integer           NOT NULL,
    update_date              timestamptz(6),
    update_user              integer,
    revision_count           integer           DEFAULT 0 NOT NULL,
    CONSTRAINT user_group_pk PRIMARY KEY (user_group_id));

    create or replace view biohub_dapi_v1.user_group as select * from biohub.user_group;

    create trigger audit_user_group before insert or update or delete on biohub.user_group for each row execute procedure tr_audit_trigger();
    create trigger journal_user_group after insert or update or delete on biohub.user_group for each row execute procedure tr_journal_trigger();

    INSERT into biohub.user_group(name,group_type,affiliation,email_address,phone_number,web_page,province_state,country,record_effective_date,create_date,revision_count, create_user)
    VALUES
      ('Elphinstone Logging Focus',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Esquimalt Municipality',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('A & A Trading Ltd.',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aquaterra Environmental Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Triton Environmental Consultants Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ken Summers Biological Services',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Victoria','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Urban Systems','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ducks Unlimited','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dendroica Environnement et Faune','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Capital Regional District (CRD)','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bird Studies Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Elevate Environmental Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nature Conservancy of Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Vancouver Island University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bianchini Biological Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bat Conservation International','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Amec Foster Wheeler','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Strategic Natural Resource Consultants, Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Himark Forest Lrd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Natural Gas Development','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Energy and Mines and Petroleum Resources','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ripley''s Aquarium of Canada','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lower Similkameent Indian Band','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('North Arrow Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Snuneymuxw First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Thompson Rivers University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Victoria','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Assessment','Org','CrownC',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Access to Secure CDC data-Arcmap','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Saanich Municipality',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fisheries and Oceans Canada (DFO)',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Timber Sales','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Saanich',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Equipose Environmental Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Current Environmental',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Municipality of Powell River',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Parks',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Vast Resource Solutions',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('COSEWIC',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Environment and Climate Change Strategy','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sustainable Elements Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Integrated Resource Consultants',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Drosera Ecological Consulting Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('The Nature Trust of BC',NULL,'NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aruncus Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('B.A. Blackwell and Associates',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Northern BC','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lil''wat Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Strategic Resource Solutions','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('A Rocha Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tetra Tech EBA','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Associated Engineering','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nova Pacific Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Atlantic Canada Conservation Data Centre','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NatureServe Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Western Forest Products','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Town of Comox','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Regional District of Central Okanagan','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Township of Langley','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sartori Environmental Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kinder Morgan Canada','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Capacity Forest Management Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Wildlife Federation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pinnacle Ecological Services',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Golder Associates',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Forests, Lands, Natural Resource Operations and Rural Development','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dillon Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fortis BC Energy Inc.',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nupqu Develoment Corporation',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Okanagan Institute for Biodiversity, Reslience and Ecosystems Services (BRAES)',NULL,'NGO',NULL,NULL,'http://braes.ok.ubc.ca',NULL,NULL,now(),now(),0,1),
      ('University of British Columbia',NULL,'Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Conservation Data Centre','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tsay Keh Dene Nation','Org','Gov-FN',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Lower Nicola Indian Band',NULL,'Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cascadia Natural Resource Consultants Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecojustice Environmental Law Clinic','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('WWF-Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Stantec','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pinchin West Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Rogers Communications Inc.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Conservation Foundation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Metro Vancouver','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Raven Ecological Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Trans Mountain Canada Pipelines Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ontario Natural Heritage Information Centre','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TimberWest Forest Corp','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Trent University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Islands Trust','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Wildlife Service',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,'CA',now(),now(),0,1),
      ('Access to Secure CDC data-iMap','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Chartwell Consultants',NULL,'Con',NULL,NULL,'www.chartwell-consultants.com',NULL,NULL,now(),now(),0,1),
      ('BC Hydro',NULL,'CrownC',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Carmel Bay Exploration',NULL,'Ind',NULL,NULL,NULL,'AB','CA',now(),now(),0,1),
      ('City of Abbotsford',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pearson Ecological',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Environmental Dynamics Inc. (EDI)',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Saulteau First Nations',NULL,'Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Transportation and Infrastructure',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecora Resource Group Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Focus Corporation',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Keystone Wildlife Research Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sea to Sky Mapping',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Oil and Gas Commission',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pandion Ecological Research Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('SNC Lavalin Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hemmera',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Columbia Environmental Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Innergex',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EDI Environmental Dynamics Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Envirowest Consultants',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Athene Ecological',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tulisso Design Group Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cabin Forestry Services Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Alberni-Clayoquot Regional District',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Summit Environmental Consultants Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CN Environment',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Department of National Defence',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Madrone Environmental Services Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('SLR Consulting Canada Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('ENKON Environmental Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Parks Conservation Risk Assessment Tool',NULL,NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 1 - Vancouver Island',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 2 - Lower Mainland',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 3 - Thompson',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 4 - Kootenay',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 5 - Cariboo',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 6 - Skeena',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 7 - Omineca',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 8 - Okanagan',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Region 9 - Peace',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('GCPE - Government Communications and Public Engagement',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('South Coast Conservation Program',NULL,'NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Phase II Ventures Ltd.',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Centre for Disease Control',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecoscape Environmenal Consultants Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Brian Wilkes and Associates Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Conservation Data Centre Contract','AdHoc','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aspen Planers Ltd.',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecofor Consulting Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('AMEC',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hedberg and Associates Consulting Ltd.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Environment and Climate Change Canada',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Kent',NULL,'Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TERA Environmental',NULL,'Con',NULL,NULL,NULL,'AB',NULL,now(),now(),0,1),
      ('University of Calgary',NULL,'Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tolko Industries Ltd.',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Morrison Hershfield',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aboriginal Affairs and Northern Development Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Shuswap Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Balance Ecological','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Surrey','Org','Gov-L',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Fraser Valley Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Strathcona Forestry Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hatfield Group','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Interfor','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('WSI Staff','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Western Water Associates Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NatureServe','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Trillium Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Okanagan-Similkameen Stewardship Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Advance Forestry Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Northwest Hardwoods','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Clean Energy BC','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecologic Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Somenos Marsh Wildlife Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Chilliwack','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Keystone Environmental Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EBB Environmental Consulting Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Regional District of Okanagan-Similkameen','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ktunaxa Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Macro Pipelines Inc','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Whistler Centre for Sustainability','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Resort Municipality of Whistler','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hupacasath First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Suncity Environmental Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Parks Canada',NULL,'Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Infinity-Pacific Stewardship Group',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tysig Ecological Research',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Genoa Environmental Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mainstream Biological Consulting',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cermaq',NULL,'Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Scott Resource Services Inc.',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Vernon Army Cadets',NULL,'NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hill Environmental',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Franz Environmental',NULL,'Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Royal BC Museum',NULL,'Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Okanagan Nation Alliance','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Econ Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Forest Ecosystem Solutions Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('AECOM','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Water''s Edge Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mimulus Biological Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Campbell River','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('National Research Council Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sage Forestry','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Namgis First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Coast Spatial Mapping','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bella Coola Community Forest Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Forsite','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Shawnigan Lake School','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Shxw''ow''hamel First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Nanaimo','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tamihi Logging Co.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Polaris Environmental Consultants Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Access to Secure Critical Habitat-imap','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Guelph','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Natural Resource Solutions Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aplin & Martin Consultants Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Blueberry River First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canada Lands Company CLC','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Robin B. Clark','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Galena Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hutchinson Environmental Sciences Ltd.','Org','Con',NULL,NULL,NULL,NULL,'CA',now(),now(),0,1),
      ('Access to Secure Critical Habitat-Arcmap','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Conifex','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('David Suzuki Foundation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Environmental Assessment Agency','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lytton First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Touchstone GIS Services Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kawa Engineering Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Iverson and Mackenzie Biological Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Castor Consultants Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aqua-Tex Scientific Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('PGL Pottinger Gaherty Environmental Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Stk''emlupsemc te Secwepemc Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aqua Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cascade Environmental Resource Group Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CH2M','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of North Vancouver','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Paraminerals','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Phoenix Environmental Services Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Caribou Ecological Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Upper Nicola Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('The Central Kootenay Invasive Plant Committee','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aarde Environmental Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kestrel Research Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Technology, Innovation and Citizens'''' Services','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Durand Ecological Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nona Phillips Forestry Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Conservation Officer Service','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Katzie First Nation','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kestrel Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Metsa Resource Management','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Valhalla Environmental Consulting Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Oregon Dept of Agriculture','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Osoyoos Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Yukon Conservation Data Centre','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Cariboo','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Kootenay/Boundary','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Northeast','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Omineca','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Skeena','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - South Coast','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - Thompson/Okanagan','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NRO Region - West Coast','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Arcadis','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ursus Environmental','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('West Fraser Mills','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Adams Lake Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kerr Wood Leidal Associates','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('HCR Environmental Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Island Timberlands','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Principal Environmental Compliance Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Salmon Arm','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DWB Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecofish Research','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of West Vancouver','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ratcliff and Company LLP','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lax Kw''alaams First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BA Blacktop Div of Interoute Construction','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Musqueam First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Kelowna','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Eco-Matters Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Alaska Natural Heritage Program','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Indigenous Relations and Reconciliation','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Greater Vancouver Water District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Yale First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Squamish First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CDC - Northwest Territories','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CMJ Project Solutions Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Amaroq Wildlife Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Indigenous and Northern Affairs Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aurora Wildlife Research','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('MacDonald Environmental Sci','Org',NULL,'mesl@shaw.ca',NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ardea Biological Consulting Ltd','Org','Con',NULL,NULL,'www.ardea.ca',NULL,NULL,now(),now(),0,1),
      ('Biolinx Environmental Research','Org','Con','biolinx@shaw.ca',NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cooper Beauchesne and Associates Ltd. - Kootenay Office','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cowichan Valley Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Black Mount Loggin Inc.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Transport Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Species and Ecosystems Data and Information Security Committee','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Salt Spring Island Conservancy','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Council on Ecological Areas (CCEA)','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Friends of Island View Beach','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of British Columbia Okanagan','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('York University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Ottawa','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ts''elxweyeqw Tribe','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aquaparian Environmental Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Saint Mary''s University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Calidris Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mining Association of Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kamloops Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dalhousie University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Associated Environmental Consultants Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Masse Environmental Consultants Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Trail','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Beckingham Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Swell Environmental Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pacheedaht First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wild Land Wood','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ophiucus Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Constance, Germany','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('McLeod Lake Indian Band Referral Office','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wild Pacific Trail Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cornice Environmental Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CN Railway','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Barsanti Environmental Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Royal Roads University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Diamond Head Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('World Wildlife Fund','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ekistics','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Longfellows Inc.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Oak Bay','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lees and Associates','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Applied Aquatic Research Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teck Coal Limited','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wilderness Committee','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lakehead University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Samahquam First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Victoria Hospice Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Saskatchewan','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Colwood','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Chu Cho Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Granby River Consulting Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Zoetica Environmental Consulting Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('McMaster University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Steer Environmental Associates Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('British Columbia Institute of Technology (BCIT)','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Claytonia','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Municipality of North Cowichan','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('I.C. Ramsay and Associates','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Polar GeoScience Ltd','Org','Con',NULL,'604-815-4548',NULL,'BC','CA',now(),now(),0,1),
      ('M.J. Milne and Associates Ltd.','Org','Con',NULL,'250-558-5770',NULL,'BC',NULL,now(),now(),0,1),
      ('Louisiana Pacific Canada Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canfor (Canadian Forest Products)','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fraser Valley Conservancy','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('New Gold Inc','Org','Ind',NULL,NULL,NULL,'BC',NULL,now(),now(),0,1),
      ('Symmtree Consulting Group Inc','Org','Con',NULL,'250-652-6509',NULL,'BC',NULL,now(),now(),0,1),
      ('Eco-Web Ecological Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aspen Wildlife Research Inc.','Org','Con','clayton.apps@telus.net','403-270-8663',NULL,NULL,NULL,now(),now(),0,1),
      ('Access to WSI layers in Arcmap','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ian Scott Planning Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Comox Valley Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Enbridge','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BCIT News','Org','Med',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kitasoo/XaiÃ¢â‚¬â„¢xais First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Leq''Amel Nation','Org','Gov-FN',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Juice FM','Org','Med',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Lake Country','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cascade Lower Canyon Community Forest','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TDB Consultants Ltd','Org','Con',NULL,'250-649-6011',NULL,'BC','CA',now(),now(),0,1),
      ('Molly Creek Forestry Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aleza Lake Research Forest','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Habitat Acquisition Trust','Org','NGO',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Columbia Power Corporation','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ucluelet First Naion','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Interoute Construction Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ulkatcho Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Allnorth','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wildlife Dynamics Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Swan Lake Nature Sanctuary','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Alberta','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('White Pine Environmental Resources Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('MiCo Properties','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Makonis Consulting Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Northwest Hydraulic Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Penticton Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Baseline Environmental Ltd','Org','Con',NULL,NULL,NULL,'Alberta',NULL,now(),now(),0,1),
      ('Mapmonsters GIS Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Okanagan Collaborative Conservation Program','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Gitanyow','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cypress Forestry Consultants','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Forest Practices Board','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Clover Point Cartographics','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Selkirk College','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Gunn and Associates','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Coquitlam','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Quest University Canada','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Naito Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Stewardship Centre for BC','Org',NULL,NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Liber Ero Program','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Carleton University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('National Council for Air and Stream Improvement INC (NCASI)','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Washington','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Davis Environmental Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bowen Island Municipality','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ancient Forest Alliance','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hardner & Gullison Associates LLC','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Strix Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dayesi Services Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Taan Forest','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Zimmfor','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Simon Fraser University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('ERM Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Jakob Dulisse Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Parks and Wilderness Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ryerson University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kootenay Conservation Program','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Washington Natural Heritage Program','Org','Gov-P',NULL,NULL,NULL,'OR','US',now(),now(),0,1),
      ('Wildlife Infometrics Ltd.','Org','Con','line.giguere@wildlifeinfometrics.com','250-997-5700','wildlifeinfometrics.com','BC','CA',now(),now(),0,1),
      ('Coldstream Ranch','Org','Ind',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Silvacare Inc.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TLC The Land Conservancy of BC','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Okanagan Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bull Houser','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Atco Wood Products Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('LGL Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Coastal Natural Resource Management','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Skeetchestn Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Skawh First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Spea Environmental Ltd','Org',NULL,NULL,NULL,'https://www.speaenvironmental.ca/',NULL,NULL,now(),now(),0,1),
      ('Creston Community Forest','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kootenay Map Masters Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('GreatPacific Consulting Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecosystem Information Section-KMB-MOE','Access','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kwikwetlem First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('KGHM Ajax Mining Inc','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Spicker GIS Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('White Bull Elk Restoration Project','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Landowners of 2004-2014 Kootenay Community Bat Project','AdHoc',NULL,NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('McElhanney Consulting Services Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teck Trail Operations','Org','Ind',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Carrier Lumber Ltd.','Org','Ind',NULL,'(250) 563-9271,',NULL,NULL,NULL,now(),now(),0,1),
      ('Roy Northern Land and Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Little Shuswap Lake Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Grand Forks','Org','Gov-L',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('The Nature Conservancy','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Stanley Park Ecology Society','Org','NGO',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Agriculture and Agri-Food Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Radio-Canada CBC','Org','Med',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Save Linley''s Hidden Ridge','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Davies Wildlife Management','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fish-Kissing Weasels Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wood plc','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Twawout Nation','Org','Gov-FN',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Ranger Forest Services Ltd.','Org','Ind',NULL,NULL,'https://biz.bcibic.ca/ranger-forest-services-ltd','BC','CA',now(),now(),0,1),
      ('Envirochem Services Inc.','Org','Ind',NULL,'604-986-0233',NULL,'BC','CA',now(),now(),0,1),
      ('South Okanagan Similkameen Conservation Fund','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Thompson-Nicola Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Valley Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pathfinder Endeavours','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EcoLogic Research','Org',NULL,NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Vaagen Fibre Canada','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Encana Services Company','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('ExxonMobil','Org','Ind',NULL,NULL,NULL,NULL,'CA',now(),now(),0,1),
      ('Clayburn Middle School','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Port Coquitlam','Org','Gov-L',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Shackan Indian Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Regional District of Central Kootenay','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mountain Pacific Environmental Consultants Limited','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('District of Summerland','Org','Gov-L',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Consus Management Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cariboo Woodlot Association','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cariboo Aboriginal Forest Enterprises','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('WSP','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EcoAmmo Sustainable Consulting Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Alces Group','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ethos Gold Corp','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Eco-concepts Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ecomotive Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fort Nelson First Nation','Org','Gov-FN',NULL,'250.774.7257',NULL,NULL,NULL,now(),now(),0,1),
      ('Brent Harley and Associates Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TRI Environmental Consulting Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dunham & Associates Forest Professionals Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sasquatch Forest Products','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Citizens'' Services','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Raincoast Applied Ecology','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Invasive Species Council of BC','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Regional District of Kootenay Boundary','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ferries','Org','CrownC',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('TRP Forestry Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Shishala Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Manning Park Resort','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('St Mary''s University','Org','Acad',NULL,NULL,NULL,'NS',NULL,now(),now(),0,1),
      ('Atlas Information Management','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Integrated ProAction Corp','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canyon Wren Consulting Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EXP Services Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Alberta Environment and Parks','Org','Gov-P',NULL,NULL,NULL,'AB','CA',now(),now(),0,1),
      ('MaPP Marine Plan Partnership','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sea to Sky Invasive Species Council','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Creston Valley Wildsight','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kalesnikoff Lumber Company Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aqua Silva','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Redcedar Environmental Consulting Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Balanced Environmental Services Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Vancouver Fraser Port Authority','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aquaculture Stewardship Council','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('White Environmental Environmental Resources Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DR Clough Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Round River Conservation Studies','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('FrontCounter BC','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Huu-ay-aht Frist Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CP Rail','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Azimuth Forestry and Mapping','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sto:lo Research and Resource Management Centre','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Nelson','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('KG Exploration','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Westpark Electric Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Maple Ridge','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Squamish Lillooet Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Weyerhaeuser','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Biowise Environmental Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aqam First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Vernon','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lake Country Environmental Health and Safety','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Save French Creek Estuary Lands','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Parsons Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Suncor Energy Products Partnership','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('JBL Environmental Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wildrock Environmental Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Gorman Bros Lumber Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('ISL Engineering and Land Services Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Pitt Meadows','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Port Moody','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Splatsin Development Corp','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kelama Forestry Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sage Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('IT International Telecom','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sumas First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Grouse Mountain Resorts','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Telkwa Coal','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Regional District of North Okanagan','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Penticton','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fraser River Pile and Dredge Inc','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Conwest Group','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Creative BC','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cypress Mountain Park','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Jacobs','Org','Con',NULL,NULL,NULL,'AB','CA',now(),now(),0,1),
      ('Corvidae Environmental Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Malahat First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sil Industrial Minerals','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Hope','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('McTavish Resource and Management Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kleinfelder, Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Office of the Auditor General','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Saanich News','Org','Med',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Simpcw Resources Group','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Zonal Ecosystem And Wildlife Consultants Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('J Hobbs Ecological Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tsain-Ko Forestry','Org','Ind',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('ClearStream Environmental Consulting Service','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mayne Island Conservancy Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('NakÃ¢â‚¬â„¢azdli Natural Resources','Org','Gov-FN','tkresearcher5@nakazdli.ca','250-996-0088',NULL,'BC','CA',now(),now(),0,1),
      ('City of Burnaby','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teal Cedar Products','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teck Metals Inc.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pathfinders Endeavors','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Coast Guard','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lawes Forest Management Ltd','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Yellow Point Ecological Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Keefer Ecological Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Grassland Conservation Council','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sage Ecological','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Goldeneye Ecological Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Town of Creston','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('WEB Engineering','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Westbank First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Aquila Conservation & Environment Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cowichan Tribes','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Core6 Environmental Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Islander Engineering','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nk''Mip Cultural Centre','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Enel Green Power','Org','Ind',NULL,NULL,'https://www.enelgreenpower.com','AB','CA',now(),now(),0,1),
      ('Frontline Operations Group Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nicola Tribal Association','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Titus Biological Services Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bonaparte First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Smart Map Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Toth and Associates Environmental Services','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wildlife Rescue Association of BC','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Industrial Forestry Service Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Binnie Consulting Ltd.','Access','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('California State Library','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Trails for Creston Valley Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Spatial Vision Group','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('EDN Forest Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teck Resources','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tsilhqotin','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bell Media','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Dunkley Lumber Ltd.','Access','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Friends of Cortes Island Society','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kiwetinohk Resources Corp','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Gandalf Ingenuity Ltd.','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Squamish','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of Queensland','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Marmot Recovery Foundation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Neskonlith Band','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Oregon State University','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Western Canadian Timber Products Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Indigenous Services Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Northland Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lime Creek Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Granby Ecological Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bring Back the Bluebird Project','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sureway Construction Group Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Xwisten First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Barkley Project Group','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Weaver Technical Corp','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bighorn Wildlife Technologies','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Calgary Zoo','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Taseko Mines Ltd (TML)','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Avison Young','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Integrated Ecological Research','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Spuzzum First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Talisker Resources Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Village of Cache Creek','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('GO Wood Forestry Services Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('D''Arcy Consulting Services','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Raincoast Conservation Foundation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kailo Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('New Gold','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DISA21PE001','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Government of Yukon','Org','Gov-P',NULL,NULL,'https://yukon.ca/en/science-and-natural-resources/fish-and-wildlife-species','YT','CA',now(),now(),0,1),
      ('Marlim Ecological Consulting Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CBRE Global Workplace Solutions','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Frontera Solutions','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('US Department of Agriculture (USDA)','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Explor','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('West Moberly First Nations','Org','Gov-FN',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Quartech','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Living Lakes Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canadian Natural Resource Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Williams Lake','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Parks Foundation','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Central Okanagan Land Trust','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mountain Pacific Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('The Dena Kayeh Institute','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Repsol','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Beecher Bay First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('LNG Canada','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('McFarland Marceau Architects','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('BC Marine Trails','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('BC Ministry of Attorney General','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wood Americas Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Central Saanich','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Technapro Forest Management','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Skeetchestn Natural Resources','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Cariboo Heights Forest Preservation Society','Org','NGO',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Aim Land','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Telus','Org','Ind',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('N''Quatqua First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Coastal Douglas-fir Conservation Partnership','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Eagle Cap Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lillooet Brewing Company','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sq''ewlets First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Snaw-naw-as First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Leaning Oaks','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Pioneer Forestry','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sustainable Kimberley','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Weststone Group','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Environmental Quality','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sts''ailes First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Skwah First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Canada Food Inspection Agency','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Imperial Oil','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Fraser Port Authority','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Gilbert Smith Forest Products Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Parklane White Pines Development','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Mission','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Kitimat','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Royal Canadian Mounted Police','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('TerraFauna Wildlife Consulting Inc.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kalispel Tribe of Indians','Org','Gov-FN',NULL,NULL,NULL,'WA','US',now(),now(),0,1),
      ('Revelstoke Review','Org','Med',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('District of Port Hardy','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Strathcona Regional District','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Glenside Ecological','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Campbell River Art Gallery','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('test please delete','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('CoastRange Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hamilton D''Ambra Consulting','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Big River Analytics','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Quebec CDC','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Big Picture Biology','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Parim Tee Solutions','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Synergy Applied Ecology','Org','Con','pamela@synergyecology.ca','250-997-3496','https://synergyecology.ca/contact/','BC','CA',now(),now(),0,1),
      ('Applied Ecological Solutions Corp','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Langford','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Vancouver Island Health Authority','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sidley Mountain Forestry Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Greenways Land Trust','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Twincon Enterprises Ltd.','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Plastic Viking Ltd','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DISA20PE002','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Matsqui First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Certes','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Burrowing Owl','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('G3 Consulting Limited','Org',NULL,NULL,NULL,'https://g3consulting.com/','BC','CA',now(),now(),0,1),
      ('Public Works and Government Services Canada','Org','Gov-Fd',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lower Kootenay Indian Band','Org','Gov-FN',NULL,NULL,NULL,'BC','CA',now(),now(),0,1),
      ('Colonial Coal International Corporation','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Ohamil First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Lake Trail Environmental','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('University of New Brunswick','Org','Acad',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('ESRI','Org',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Teranis Consulting ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('T''it''q''et First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Chawathil','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Marine Toad Enterprises Inc','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Wildlife Conservation Society Canada','Org','NGO',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('T''kemlups te Secwepemc','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Mosaic Forests','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Quinsam Coal','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('City of Kamloops','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Peka Enterprises Ltd','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Tsawout First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Bearfoot Resources Ltd.','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Government of Alberta','Org','Gov-P',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DISA20PE001','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Hatch','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Nak''azdli Whut''en','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Village of Slocan','Org','Gov-L',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Letts Environmental Consultants','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Klohn Crippen Berger','Org','Con',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('DISA20PE003','Access',NULL,NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Sasquatch Mountain Resort','Org','Ind',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Kwanlin Dun First Nation','Org','Gov-FN',NULL,NULL,NULL,NULL,NULL,now(),now(),0,1),
      ('Reciprocity Research','Org','Con',NULL,NULL,NULL,'BC','CA',now(),now(),0,1);

      CREATE TABLE user_user_group(
        user_user_group_id          integer           GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
        user_group_id               integer           NOT NULL,
        system_user_id              integer           NOT NULL,
        create_date                 timestamptz(6)    DEFAULT now() NOT NULL,
        create_user                 integer           NOT NULL,
        update_date                 timestamptz(6),
        update_user                 integer,
        revision_count              integer           DEFAULT 0 NOT NULL,
        CONSTRAINT user_user_group_pk PRIMARY KEY (user_user_group_id)
    );

    ALTER TABLE user_user_group ADD CONSTRAINT "Refsystem_uug_1"
    FOREIGN KEY (system_user_id)
    REFERENCES system_user(system_user_id)
  ;

  ALTER TABLE user_user_group ADD CONSTRAINT "Refuug_2"
      FOREIGN KEY (user_group_id)
      REFERENCES user_group(user_group_id)
  ;

  create or replace view biohub_dapi_v1.user_user_group as select * from biohub.user_user_group;

  create trigger audit_user_user_group before insert or update or delete on biohub.user_user_group for each row execute procedure tr_audit_trigger();
  create trigger journal_user_user_group after insert or update or delete on biohub.user_user_group for each row execute procedure tr_journal_trigger();

  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`

  drop TABLE user_group;

  `);
}
