import { Knex } from 'knex';

/**
 * Update funding_source lookup table to include additional values.
 * 
 * Specifically, include the values from the static coordinator agencies list.
 *
 * @export
 * @param {Knex} knex
 * @return {*}  {Promise<void>}
 */
export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
	set search_path=biohub,public;

    insert into funding_source 
      (name, record_effective_date, project_id_optional) 
    values
      ('A Rocha Canada', now(), TRUE),
      ('Aarde Environmental Ltd.', now(), TRUE),
      ('Acres Consulting', now(), TRUE),
      ('Advisian', now(), TRUE),
      ('AECOM Canada Ltd.', now(), TRUE),
      ('Alaska Department of Fish and Game', now(), TRUE),
      ('Alces Environmental Ltd.', now(), TRUE),
      ('Allnorth Consultants Limited', now(), TRUE),
      ('Allouette River Management Society', now(), TRUE),
      ('AMEC Earth and Environmental', now(), TRUE),
      ('Applied Aquatic Research Ltd.', now(), TRUE),
      ('Applied Ecological Solutions Corp.', now(), TRUE),
      ('Aquaparian Environmental Consulting Ltd.', now(), TRUE),
      ('AquaSilva Resource Management Ltd.', now(), TRUE),
      ('Aqua-Tex Scientific Consulting Ltd. ', now(), TRUE),
      ('Associated Environmental Consultants Inc.', now(), TRUE),
      ('Association of Wetland Stewards for Clayoquot and Barkley Sounds', now(), TRUE),
      ('Assuage Environmental Ltd.', now(), TRUE),
      ('Aurico Metals Inc.', now(), TRUE),
      ('Avison Management Services Ltd.', now(), TRUE),
      ('Azimuth Consulting Group Partnership', now(), TRUE),
      ('Balanced Ecological Management Company', now(), TRUE),
      ('Bamfield Marine Sciences Centre', now(), TRUE),
      ('BBA Engineering Ltd.', now(), TRUE),
      ('BC Conservation Foundation (BCCF)', now(), TRUE),
      ('BC Hydro', now(), TRUE),
      ('BCIT Fish Wildlife and Recreation Program', now(), TRUE),
      ('Burt and Associates', now(), TRUE),
      ('Canadian Forest Products', now(), TRUE),
      ('Capital Regional District (CRD)', now(), TRUE),
      ('Cariboo Environmental Quality Consulting Ltd.', now(), TRUE),
      ('Cariboo Envirotech Ltd.', now(), TRUE),
      ('Carleton University', now(), TRUE),
      ('Cascade Environmental Resource Group Ltd.', now(), TRUE),
      ('Castus Environmental Services Ltd.', now(), TRUE),
      ('Central Westcoast Forest Society', now(), TRUE),
      ('Chu Cho Environmental', now(), TRUE),
      ('City of Abbotsford', now(), TRUE),
      ('City of Chilliwack', now(), TRUE),
      ('City of Coquitlam', now(), TRUE),
      ('City of Kelowna Environment Division', now(), TRUE),
      ('Clark University', now(), TRUE),
      ('Clearwater Environmental Consulting', now(), TRUE),
      ('Coast River Environmental Services Ltd.', now(), TRUE),
      ('Coldstream Ecology Ltd.', now(), TRUE),
      ('College of New Caledonia', now(), TRUE),
      ('Columbia Environmental Consulting Ltd.', now(), TRUE),
      ('Columbia Power Corporation', now(), TRUE),
      ('Colville Confederated Tribes Fish and Wildlife', now(), TRUE),
      ('Comox Valley Project Watershed Society', now(), TRUE),
      ('Cooper Beauchesne and Associates Ltd.', now(), TRUE),
      ('Copcan Contracting Ltd.', now(), TRUE),
      ('Cornice Environmental Consulting Ltd.', now(), TRUE),
      ('Corvidae Environmental Consulting Inc.', now(), TRUE),
      ('Crane Creek Enterprises', now(), TRUE),
      ('CSR Environmental Ltd.', now(), TRUE),
      ('Current Environmental Ltd.', now(), TRUE),
      ('D. Burt and Associates', now(), TRUE),
      ('D.R. Clough Consulting', now(), TRUE),
      ('David Bustard and Associates Ltd.', now(), TRUE),
      ('Davis Environmental Ltd.', now(), TRUE),
      ('Dayesi Services', now(), TRUE),
      ('Department of Fisheries and Oceans (DFO)', now(), TRUE),
      ('DGR Consulting', now(), TRUE),
      ('Dillon Consulting Limited', now(), TRUE),
      ('District of Kent', now(), TRUE),
      ('District of North Vancouver', now(), TRUE),
      ('District of Saanich', now(), TRUE),
      ('Diversified Environmental Services Ltd.', now(), TRUE),
      ('DWB Consulting Services Ltd.', now(), TRUE),
      ('East Carolina University - Department of Biology', now(), TRUE),
      ('EBB Environmental Consulting Inc.', now(), TRUE),
      ('Ecofish Research Ltd.', now(), TRUE),
      ('Ecofor Consulting', now(), TRUE),
      ('Ecologic Consulting Ltd.', now(), TRUE),
      ('EcoMetrix Incorporated', now(), TRUE),
      ('Ecora Engineering and Resource Group Ltd.', now(), TRUE),
      ('Ecoscape Environmental Consultants Ltd.', now(), TRUE),
      ('Eco-Web Ecological Consulting Ltd.', now(), TRUE),
      ('EDI Environmental Dynamics Inc.', now(), TRUE),
      ('Elevate Environmental Inc.', now(), TRUE),
      ('Elk River Alliance', now(), TRUE),
      ('ENKON Environmental Ltd.', now(), TRUE),
      ('Envirologic Consulting Inc.', now(), TRUE),
      ('Environment and Climate Change Canada', now(), TRUE),
      ('Envirowest Consultants Inc.', now(), TRUE),
      ('ERM Consultants Canada Ltd.', now(), TRUE),
      ('Esther Guimond Consulting', now(), TRUE),
      ('Estsek Environmental Services LLP', now(), TRUE),
      ('EXP Services Inc.', now(), TRUE),
      ('FINS Consulting Ltd.', now(), TRUE),
      ('Fish-Kissing Weasels Environmental', now(), TRUE),
      ('ForFish Consulting', now(), TRUE),
      ('Forsite Consultants Ltd.', now(), TRUE),
      ('FortisBC', now(), TRUE),
      ('Fraser Valley Watersheds Coalition', now(), TRUE),
      ('Freshwater Fisheries Society of BC', now(), TRUE),
      ('FSCI Biological Concultants', now(), TRUE),
      ('G3 Consulting Ltd.', now(), TRUE),
      ('GeoMarine Environmental Consultants Ltd.', now(), TRUE),
      ('GG Oliver and Associates Environmental Science', now(), TRUE),
      ('Gitanyow Fisheries Authority', now(), TRUE),
      ('Gitksan Watershed Authorities', now(), TRUE),
      ('Golder Associates Ltd.', now(), TRUE),
      ('Grassroots Environmental Services', now(), TRUE),
      ('Hatfield Consulting Ltd.', now(), TRUE),
      ('HCR Environmental Consulting', now(), TRUE),
      ('Hemmera', now(), TRUE),
      ('High Country Consulting', now(), TRUE),
      ('Hill Environmental Ltd.', now(), TRUE),
      ('Hocquard Consulting', now(), TRUE),
      ('I.C. Ramsay and Associates', now(), TRUE),
      ('Ingersol Mountain Enterprise Ltd.', now(), TRUE),
      ('Inland Timber Management Ltd.', now(), TRUE),
      ('InStream Fisheries Research Inc.', now(), TRUE),
      ('Interior Reforestation Co. Ltd.', now(), TRUE),
      ('IRC Integrated Resource Consultants Inc.', now(), TRUE),
      ('ISL Engineering and Land Services Ltd.', now(), TRUE),
      ('Iverson & MacKenzie Biological Consulting Ltd.', now(), TRUE),
      ('Jacobs Canada Inc.', now(), TRUE),
      ('JBL Environmental Services Ltd.', now(), TRUE),
      ('Karen L Grainger', now(), TRUE),
      ('Kawa Enginnering Ltd.', now(), TRUE),
      ('Kerr Wood Leidal Associates Ltd.', now(), TRUE),
      ('Keystone Environmental Ltd.', now(), TRUE),
      ('Klohn Crippen Berger Ltd.', now(), TRUE),
      ('Knight Piesold Ltd.', now(), TRUE),
      ('Ktunaxa Nation Council', now(), TRUE),
      ('Lake Trail Environmental Consulting', now(), TRUE),
      ('Letts Environmental Consultants Ltd.', now(), TRUE),
      ('LGL Limited', now(), TRUE),
      ('Lheidli T Enneh First Nations', now(), TRUE),
      ('Limnotek Research and Development Inc.', now(), TRUE),
      ('Living Resources Environmental', now(), TRUE),
      ('Lorax Environmental Services Ltd.', now(), TRUE),
      ('Lotic Environmental Ltd.', now(), TRUE),
      ('M.C. Wright and Associates Ltd.', now(), TRUE),
      ('Madrone Environmental Services Ltd.', now(), TRUE),
      ('Mainstream Aquatics Ltd.', now(), TRUE),
      ('Mainstream Biological Consulting Inc.', now(), TRUE),
      ('Marine Harvest Canada', now(), TRUE),
      ('Marlim Ecological Consulting Ltd.', now(), TRUE),
      ('Masse Environmental Consultants Ltd.', now(), TRUE),
      ('Matrix Solutions Inc.', now(), TRUE),
      ('Max Planck Institute, Ploen, Germany', now(), TRUE),
      ('McCleary Aquatic Systems Consulting', now(), TRUE),
      ('McElhanney Ltd.', now(), TRUE),
      ('McGill University, Redpath Museum', now(), TRUE),
      ('McTavish Resource & Management Consultants Ltd.', now(), TRUE),
      ('Metro Vancouver (GVRD)', now(), TRUE),
      ('Metro Vancouver Regional Parks', now(), TRUE),
      ('Michigan State University', now(), TRUE),
      ('Mid Vancouver Island Habitat Enhancement Society', now(), TRUE),
      ('Ministry of Environment & Climate Change Strategy', now(), TRUE),
      ('Ministry of Forests', now(), TRUE),
      ('Ministry of Forests, Lands, Natural Resource Operations & Rural Development', now(), TRUE),
      ('Ministry of Lands, Water, and Resource Stewardship', now(), TRUE),
      ('Ministry of Transportation & Infrastructure', now(), TRUE),
      ('Minnow Environmental Inc.', now(), TRUE),
      ('Montana Fish, Wildlife & Parks', now(), TRUE),
      ('Mount Polley Mining Corporation', now(), TRUE),
      ('Mountain Water Research', now(), TRUE),
      ('Naito Environmental', now(), TRUE),
      ('Natural Resources Training Group (NRTG)', now(), TRUE),
      ('Nature Conservancy of Canada', now(), TRUE),
      ('Nautilus Environmental Company Ltd.', now(), TRUE),
      ('Nicola Valley Institute of Technology (NVIT)', now(), TRUE),
      ('North Coast Skeena First Nations Stewardship Society', now(), TRUE),
      ('North River Consulting Ltd.', now(), TRUE),
      ('Northern (Arctic) Federal University (NArFU)', now(), TRUE),
      ('Northern Van Island Salmonid Enhancement Assoc.', now(), TRUE),
      ('Northland Environmental Ltd.', now(), TRUE),
      ('Northwest Community College', now(), TRUE),
      ('Nova Pacific Environmental Ltd.', now(), TRUE),
      ('Nupqu Development Corporation', now(), TRUE),
      ('Ogopogo Environmental & Engineering Consultants Ltd.', now(), TRUE),
      ('Okanagan Nation Alliance', now(), TRUE),
      ('Pacificus Biological Services Ltd.', now(), TRUE),
      ('Palmer Environmental Consulting Group Inc.', now(), TRUE),
      ('Pearson Ecological', now(), TRUE),
      ('Peninsula Streams Society', now(), TRUE),
      ('Phoenix Environmental Services Ltd.', now(), TRUE),
      ('Pinchin Ltd.', now(), TRUE),
      ('Poisson Consulting Ltd.', now(), TRUE),
      ('Polaris Environmental Consultants Ltd.', now(), TRUE),
      ('Pottinger Gaherty Environmental Consultants Ltd.', now(), TRUE),
      ('Profor Resource Development Inc.', now(), TRUE),
      ('Qqs Projects Society', now(), TRUE),
      ('Quatse River Hatchery', now(), TRUE),
      ('Quesnel River Environmental Restoration Services', now(), TRUE),
      ('Red Chris Development Company Ltd.', now(), TRUE),
      ('Redcedar Environmental Consulting Inc.', now(), TRUE),
      ('Resort Municipality of Whistler', now(), TRUE),
      ('Roy Northern Environmental Ltd.', now(), TRUE),
      ('Sage Environmental Consulting Ltd.', now(), TRUE),
      ('Salmon Coast Field Station Society', now(), TRUE),
      ('Sartori Environmental Services Inc.', now(), TRUE),
      ('School District 54', now(), TRUE),
      ('Secwepemc Fisheries Commission', now(), TRUE),
      ('Selkirk College', now(), TRUE),
      ('SER Environmental Management', now(), TRUE),
      ('Seven Generations Environmental Services Ltd.', now(), TRUE),
      ('Shawn Hamilton and Associates', now(), TRUE),
      ('Shawnigan Lake School', now(), TRUE),
      ('Shuksan Fisheries Consulting', now(), TRUE),
      ('Silvatech Consulting Ltd.', now(), TRUE),
      ('Simon Fraser University (SFU) - Biological Sciences', now(), TRUE),
      ('SKR Consultants Ltd.', now(), TRUE),
      ('SLR Consulting (Canada) Ltd.', now(), TRUE),
      ('SNC Lavalin Inc.', now(), TRUE),
      ('Splatsin DC - Yucwmenlucwu LLC', now(), TRUE),
      ('St at imc Eco-Resources Ltd.', now(), TRUE),
      ('Stanley Park Ecology Society', now(), TRUE),
      ('Stantec Consulting Ltd.', now(), TRUE),
      ('Strategic Forest Management Inc.', now(), TRUE),
      ('Strategic Natural Resource Consultants Inc.', now(), TRUE),
      ('Sunshine Coast Salmonid Enhancement Society', now(), TRUE),
      ('Taan Forest Ltd.', now(), TRUE),
      ('Teck Coal Limited', now(), TRUE),
      ('Teck Highland Valley Copper Partnership', now(), TRUE),
      ('TERA Planning Ltd.', now(), TRUE),
      ('Tetra Tech Canada Inc.', now(), TRUE),
      ('Tetra Tech EBA', now(), TRUE),
      ('Thompson Rivers University', now(), TRUE),
      ('Tisdale Environmental Consulting Inc.', now(), TRUE),
      ('Titus Biological Services Inc.', now(), TRUE),
      ('Toba Montrose Hydro Inc.', now(), TRUE),
      ('Trinity Western University', now(), TRUE),
      ('Triton Environmental Consultants Ltd.', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Calgary)', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Kamloops)', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Nanaimo)', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Prince George)', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Richmond)', now(), TRUE),
      ('Triton Environmental Consultants Ltd. (Terrace)', now(), TRUE),
      ('University of Alberta', now(), TRUE),
      ('University of Bern, Institute of Ecology and Evolution', now(), TRUE),
      ('University of British Columbia', now(), TRUE),
      ('University of British Columbia (UBC) - Okanagan', now(), TRUE),
      ('University of Calgary', now(), TRUE),
      ('University of Lethbridge', now(), TRUE),
      ('University of Montana', now(), TRUE),
      ('University of Montreal', now(), TRUE),
      ('University of New Brunswick', now(), TRUE),
      ('University of Northern British Columbia', now(), TRUE),
      ('University of Texas at Austin', now(), TRUE),
      ('University of Victoria', now(), TRUE),
      ('Urban Systems Ltd.', now(), TRUE),
      ('uTree Environmental Consultants Ltd.', now(), TRUE),
      ('Valley Environmental', now(), TRUE),
      ('Vancouver Island University', now(), TRUE),
      ('Vast Resource Solutions Inc.', now(), TRUE),
      ('Vision Marine Consulting Ltd.', now(), TRUE),
      ('Wapta Environmental Consulting Ltd.', now(), TRUE),
      ('Watershed Ecological Services Ltd.', now(), TRUE),
      ('Western Forest Products Inc.', now(), TRUE),
      ('Western Water Associates Ltd.', now(), TRUE),
      ('Westland Resources Ltd.', now(), TRUE),
      ('Westslope Fisheries', now(), TRUE),
      ('White Pine Environmental Resources Inc.', now(), TRUE),
      ('Whitehead Environmental Consultants Ltd.', now(), TRUE),
      ('Wildlife Infometrics Inc.', now(), TRUE),
      ('Wood PLC', now(), TRUE),
      ('WorleyParsons Canada Service Ltd.', now(), TRUE),
      ('WSP Canada Inc.', now(), TRUE),
      ('Yukon Energy Corporation', now(), TRUE),
      ('Other', now(), TRUE);

    set search_path=biohub_dapi_v1;

    create or replace view funding_source as select * from biohub.funding_source;
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(``);
}
