# Add automated comments to the PR
name: Add Comments

on:
  pull_request:
    types: [opened, ready_for_review]
    branches-ignore:
      - test
      - prod

jobs:
  addOpenshiftURLComment:
    name: Add OpenShift URL Comment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Add Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            OpenShift URLs for the PR Deployment:
            - App Route: https://biohubbc-app-${{ github.event.number }}-${{ vars.OPENSHIFT_LICENSE_PLATE }}-dev.apps.silver.devops.gov.bc.ca/
            - API Route: https://biohubbc-api-${{ github.event.number }}-${{ vars.OPENSHIFT_LICENSE_PLATE }}-dev.apps.silver.devops.gov.bc.ca/
            - Pods: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/${{ vars.OPENSHIFT_LICENSE_PLATE }}-dev/pods?name=${{ github.event.number }}
            - Helm Release: https://console.apps.silver.devops.gov.bc.ca/helm-releases/ns/${{ vars.OPENSHIFT_LICENSE_PLATE }}-dev/release/pr-${{ github.event.number }}