# Clean out all deployment artifacts when a PR is merged against a non-standard base branch (aka: neither dev, test, or prod)
# Standard branches (aka: dev, test, prod) have their own cleanup routine that runs as part of the deployStatic action.
name: Clean Merged PR Artifacts

on:
  pull_request:
    types: [closed]
    branches-ignore:
      - dev
      - test
      - prod

jobs:
  clean:
    name: Clean Deployment Artifacts for API and App in Dev and Tools environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Only run if the PR was merged
    if: ${{ github.event.pull_request.merged == true }}
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      # Install oc, which was removed from the ubuntu-latest image in v24.04
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.16"

      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: oc login --token=${{ secrets.TOOLS_SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443

      # Clean all deployment artifacts for the PR
      - name: Clean Deployment Artifacts
        env:
          POD_SELECTOR: biohubbc
        run: |
          echo "Cleaning deployment artifacts for PR $PR_NUMBER"
          
          # Clean from dev namespace
          echo "Cleaning from af2668-dev namespace..."
          oc --namespace af2668-dev get all,pvc,secret,pods,ReplicationController,Deployment,HorizontalPodAutoscaler,imagestreamtag -o name | grep $POD_SELECTOR | grep $PR_NUMBER | awk '{print "oc delete --ignore-not-found " $1}' | bash || echo "No resources found in dev namespace"
          
          # Clean from tools namespace
          echo "Cleaning from af2668-tools namespace..."
          oc --namespace af2668-tools get all,pvc,secret,pods,ReplicationController,Deployment,HorizontalPodAutoscaler,imagestreamtag -o name | grep $POD_SELECTOR | grep $PR_NUMBER | awk '{print "oc delete --ignore-not-found " $1}' | bash || echo "No resources found in tools namespace"
          
          echo "Cleanup completed for PR $PR_NUMBER"
