name: Formating Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  format:
    name: Running Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache database node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-database-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('database/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install database dependencies
        working-directory: database
        run: npm install

      - name: Run database formatter
        working-directory: database
        run: CI=true npm run format

      - name: Cache api node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-api-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install api dependencies
        working-directory: api
        run: npm install

      - name: Run api formater
        working-directory: api
        run: CI=true npm run format

      - name: Cache app node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-app-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install app dependencies
        working-directory: app
        run: npm install

      - name: Run app formater
        working-directory: app
        run: CI=true npm run format
