name: jira-transition
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - dev

jobs:
  jiralogin:
    name: Jira Login
    runs-on: ubuntu-16.04
    env:
      JIRA_ID: ""
    steps:
      - name: jira login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Get Jira ID from title
        uses: atlassian/gajira-login@master
        run: |
          env.JIRA_ID==$([[ ${GITHUB_REF#refs/heads/} =~ ([A-Za-z]{4}[\- ]?[0-9]{3,4}) ]] && tr ' ' '-' <<< ${BASH_REMATCH[1]^^})
          echo env.JIRA_ID
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_REF}
      - name: set transition
        uses: tuanddd/jira-automate-transition@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: Peer Review
          column-to-move-to-when-changes-requested: In Progress
          column-to-move-to-when-merged: Client Review
          jira-issue-id: env.JIRA_ID
