kind: Template
apiVersion: template.openshift.io/v1
labels:
  template: postgresql-persistent-template
metadata:
  name: biohubbc-db-dc
  labels:
    build: biohubbc-db
parameters:
  - name: NAME
    displayName: Database Service Name
    description: The name of the OpenShift Service exposed for the database.
    required: true
    value: 'postgresql'

  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: The name of the OpenShift Service exposed for the database.
    required: true
    value: 'postgresql'

  - name: POSTGRESQL_USER
    displayName: PostgreSQL Connection Username
    description: Username for PostgreSQL user that will be used for accessing the database.
    required: true
    value: 'postgres'
  - name: POSTGRESQL_ADMIN_USER
    displayName: PostgreSQL Admin Connection Username
    description: Admin Username for PostgreSQL user that will be used for accessing the database.
    required: true
    value: 'postgres'

  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL Connection Password
    description: Password for the PostgreSQL connection user.
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    required: true
  - name: POSTGRESQL_ADMIN_PASSWORD
    displayName: PostgreSQL Admin Connection Password
    description: Password for the PostgreSQL admin user.
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    required: true

  - name: VOLUME_CAPACITY
    displayName: Volume Capacity
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    required: true
    value: '500Mi'
  - name: TZ
    displayName: Time Zone
    description: Database timezone
    required: false
    value: 'America/Vancouver'

  - name: IMAGE_STREAM_NAME
    displayName: IMAGE_STREAM_NAME
    description: The OpenShift ImageStream name.
    value: 'crunchy-postgres-gis'
  - name: IMAGE_STREAM_NAMESPACE
    displayName: Namespace
    description: The OpenShift Namespace where the ImageStream resides.
    value: 'af2668-tools'
  - name: IMAGE_STREAM_VERSION
    displayName: Version of PostgreSQL Image
    description: Version of PostgreSQL image to be used (9.2, 9.4, 9.5 or latest).
    required: true
    value: 'ubi8-16.2-3.4-0'

  - name: PG_DATABASE
    displayName: PostgreSQL Database Name
    description: Name of the PostgreSQL database accessed.
    value: 'biohubbc'
    required: true
  - name: PG_PRIMARY_PORT
    displayName: PostgreSQL Primary Port
    description: PostgreSQL primary port.
    value: '5432'
    required: true
  - name: PG_MODE
    displayName: PostgreSQL Mode
    description: PostgreSQL mode (primary, replica, set).
    value: 'primary'
    required: true
  - description: Set this value to override the /pgdata directory name. By default the hostname of the container is used, which does not work well in OpenShift.
    displayName: PGDATA Path Override
    name: PGDATA_PATH_OVERRIDE
    value: 'biohubbc'
    required: true

  - name: CPU_REQUEST
    value: '50m'
  - name: CPU_LIMIT
    value: '200m'
  - name: MEMORY_REQUEST
    value: '100Mi'
  - name: MEMORY_LIMIT
    value: '2Gi'
  - name: REPLICAS
    value: '1'
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-database-name: "{.data['database-name']}"
        template.openshift.io/expose-database-user: "{.data['database-user']}"
        template.openshift.io/expose-database-user-password: "{.data['database-user-password']}"
        template.openshift.io/expose-database-admin: "{.data['database-admin']}"
        template.openshift.io/expose-database-admin-password: "{.data['database-admin-password']}"
        as-copy-of: biohubbc-creds
      name: '${DATABASE_SERVICE_NAME}'
    stringData:
      database-name: '${POSTGRESQL_DATABASE}'
      database-user: '${POSTGRESQL_USER}'
      database-user-password: '${POSTGRESQL_PASSWORD}'
      database-admin: '${POSTGRESQL_ADMIN_USER}'
      database-admin-password: '${POSTGRESQL_ADMIN_PASSWORD}'

  - kind: Service
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
      name: '${DATABASE_SERVICE_NAME}'
    spec:
      ports:
        - name: postgresql
          nodePort: 0
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: '${DATABASE_SERVICE_NAME}'
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: '${DATABASE_SERVICE_NAME}'
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: '${VOLUME_CAPACITY}'
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: '${IMAGE_STREAM_NAME}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: '${DATABASE_SERVICE_NAME}'
    spec:
      replicas: ${{REPLICAS}}
      selector:
        name: '${DATABASE_SERVICE_NAME}'
      strategy:
        type: Recreate
        maxSurge: 50%
        maxUnavailable: 0
      template:
        metadata:
          labels:
            name: '${DATABASE_SERVICE_NAME}'
            role: db
        spec:
          containers:
            - name: postgresql
              env:
                - name: PG_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-user-password
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_PRIMARY_PORT
                  value: '5432'
                - name: PG_PRIMARY_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_PRIMARY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-user-password
                      name: '${DATABASE_SERVICE_NAME}'
                - name: PG_MODE
                  value: 'primary'
                - name: MODE
                  value: 'postgres'
                - name: PGOPTIONS
                  value: '-c maintenance_work_mem=128MB'
                - name: PGTZ
                  value: '${TZ}'
                - name: PGDATA_PATH_OVERRIDE
                  value: '${PGDATA_PATH_OVERRIDE}'
              image: ' '
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 5432
                  protocol: TCP
              startupProbe:
                exec:
                  command:
                    - '/bin/sh'
                    - '-i'
                    - '-c'
                    - pg_isready -h 127.0.0.1 -q -t 10
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 10
              readinessProbe:
                exec:
                  command:
                    - '/bin/sh'
                    - '-i'
                    - '-c'
                    - pg_isready -h 127.0.0.1 -q -t10
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 10
              livenessProbe:
                tcpSocket:
                  port: 5432
                initialDelaySeconds: 10
                periodSeconds: 15
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 10
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: '/dev/termination-log'
              volumeMounts:
                - mountPath: '/pgdata'
                  name: '${DATABASE_SERVICE_NAME}-data'
                - mountPath: '/var/run/postgresql'
                  name: '${DATABASE_SERVICE_NAME}-run'
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: '${DATABASE_SERVICE_NAME}-data'
              persistentVolumeClaim:
                claimName: '${DATABASE_SERVICE_NAME}'
            - name: '${DATABASE_SERVICE_NAME}-run'
              emptyDir: {}
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: '${IMAGE_STREAM_NAME}:${IMAGE_STREAM_VERSION}'
              namespace: '${IMAGE_STREAM_NAMESPACE}'
            lastTriggeredImage: ''
          type: ImageChange
        - type: ConfigChange
