kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAME
    value: biohubbc-db-setup
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        description: Database setup image stream
      labels:
        shared: 'true'
      generation: 0
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
